// Meme Melee — Card Deck
// "Black cards" are meme images, "White cards" are caption cards
// Images are static files in client/public/images/meme-melee/

// ── MEME IMAGE CARDS (Black Cards) ──────────────────────────
// Each has a category, imageUrl, alt text, and pick count
export const memeCards = [
  // ── Animals Being People ──
  { imageUrl: '/images/meme-melee/meme-01.png', alt: 'stressed pigeon in business suit', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-02.png', alt: 'surprised lion cub', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-04.png', alt: 'cool dog on beach', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-05.png', alt: 'cat demanding food at table', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-06.png', alt: 'superhero squirrel on acorn', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-07.png', alt: 'sloth running marathon', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-08.png', alt: 'ducks graduating', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-09.png', alt: 'giraffe hiding behind bush', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-10.png', alt: 'bear baking disaster', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-11.png', alt: 'hamster driving monster truck', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-12.png', alt: 'sheep doing yoga', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-14.png', alt: 'grumpy octopus king', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-15.png', alt: 'eagle dropping fry', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-17.png', alt: 'cat wizard casting spell', pick: 1, category: 'animals' },

  // ── Everyday Struggles ──
  { imageUrl: '/images/meme-melee/meme-03.png', alt: 'elderly person confused by phone', pick: 1, category: 'everyday' },
  { imageUrl: '/images/meme-melee/meme-16.png', alt: 'office workers in animal costumes', pick: 1, category: 'everyday' },
  { imageUrl: '/images/meme-melee/meme-18.png', alt: 'person failing to open jar', pick: 1, category: 'everyday' },
  { imageUrl: '/images/meme-melee/meme-19.png', alt: 'child drawing come to life', pick: 1, category: 'everyday' },
  { imageUrl: '/images/meme-melee/meme-20.png', alt: 'gnome backyard party', pick: 1, category: 'everyday' },

  // ── Weird Situations ──
  { imageUrl: '/images/meme-melee/meme-13.png', alt: 'alien tourist selfie', pick: 1, category: 'weird' },
];

// Image generation prompts — used by generate-memes.js to create meme images
// Index matches meme-XX.png numbering
export const memePrompts = [
  'A highly stressed pigeon wearing a tiny business suit, frantically typing on a laptop with multiple overflowing coffee cups, surrounded by crumpled papers. Photorealistic meme-worthy style, dramatic lighting.',
  'A majestic lion cub making an extremely surprised face, eyes wide, mouth open in a perfect O of shock. Close-up portrait, viral meme style.',
  'An elderly person holding a smartphone upside down with a look of utter confusion and mild panic, wearing reading glasses on their forehead. Candid photo style.',
  'A dog wearing oversized sunglasses and a Hawaiian shirt, sipping a tiny cocktail with a straw, utterly relaxed on a miniature beach towel. Vibrant social media colors.',
  'A cat sitting at a dinner table with a knife and fork, staring intently and very displeased at an empty plate, demanding food with its eyes. Renaissance painting style.',
  'A squirrel in a flowing superhero cape, striking a dramatic pose on top of a giant acorn, looking overly confident. Action movie poster style.',
  'A very tired-looking sloth attempting to run a marathon, barely moving, dripping sweat with existential dread. Sports photography style.',
  'A group of ducks in single-file line wearing tiny graduation caps with scholarly expressions, marching towards a library.',
  'A bewildered giraffe trying to hide behind a small garden bush, with most of its neck visible, looking embarrassed.',
  'A bear in a chef hat attempting to bake, kitchen in total disaster: flour explosions, burnt pans, bewildered despair.',
  'A tiny hamster driving a monster truck through a miniature obstacle course made of household items, intensely focused.',
  'A very fluffy sheep attempting advanced yoga, tangled up, looking perplexed and stuck.',
  'An alien tourist with oversized eyes taking a selfie in front of a mundane fire hydrant, absolutely thrilled.',
  'A grumpy octopus wearing a tiny crooked crown, on a seashell throne, immensely annoyed by its subjects.',
  'A majestic eagle dramatically dropping a single french fry from its talons, looking utterly distraught.',
  'Office workers in ridiculous animal costumes having a very serious corporate boardroom meeting.',
  'A cat wearing a sparkling wizard hat casting a spell with an outstretched paw, surrounded by magical glow.',
  'A person dramatically failing to open a jar of pickles, sweat and defeat. Dramatic close-up.',
  'A child\'s crayon drawing of a monster brought to life, confused and embarrassed to exist. Mixed media.',
  'Garden gnomes throwing a wild tiny backyard party with disco lights and miniature boombox.',
  // 21-40: Expansion batch
  'A raccoon in a trench coat trying to sneak into a movie theater, looking extremely suspicious.',
  'A very confused golden retriever wearing a lab coat, staring at a chalkboard full of complex equations.',
  'A penguin in a hawaiian shirt looking lost in a desert, holding an upside-down map.',
  'A cat caught mid-crime standing on a kitchen counter, frozen, staring directly at the camera with wide eyes.',
  'Two seagulls aggressively fighting over a single french fry on a boardwalk, dramatic action shot.',
  'A very small chihuahua sitting in an enormous armchair at a boardroom table, looking like a tiny CEO.',
  'A group of meerkats in matching track suits doing synchronized exercise, one clearly not keeping up.',
  'A dramatic close-up of a fish in a fishbowl making an unimpressed face at a terrible magic trick.',
  'A confident rooster strutting down a fashion runway with dramatic lighting and a feathery outfit.',
  'A panda bear sitting on a couch eating chips, absolutely refusing to move, extreme couch-potato energy.',
  'An owl wearing reading glasses, hunched over a tiny laptop at 3 AM, looking exhausted and caffeinated.',
  'A golden retriever in a lifeguard outfit sitting in a tall chair, staring intensely at an empty pool.',
  'Two cats in boxing gloves facing off in a tiny boxing ring, one terrified, the other overconfident.',
  'A duck wearing a tiny monocle and top hat, reading a newspaper at a cafe, looking distinguished.',
  'A group of pigeons in tactical gear, lined up like a SWAT team, looking overly serious.',
  'A tortoise wearing tiny racing goggles at a starting line, looking extremely determined.',
  'A frog sitting on a lily pad in a philosophical thinking pose, tiny chin on hand.',
  'A squirrel having a dramatic mid-air jump fail between two branches, face frozen in panic.',
  'A very fluffy alpaca at a hair salon, looking fabulous after a dramatic blowout.',
  'A baby elephant trying to fit into a kiddie pool way too small for it, splashing everywhere.',
  // 41-60: More expansion
  'A goat standing on top of a car in a parking lot, looking like it owns the place.',
  'A deer caught in headlights but literally frozen mid-dance pose.',
  'A parrot in a courtroom at the witness stand, looking like it is about to snitch.',
  'A group of flamingos standing in a circle like a very important board meeting.',
  'A dog trying to catch a ball but making the most ridiculous derp face mid-jump.',
  'A gorilla wearing a tiny birthday hat, blowing out candles, looking mildly annoyed.',
  'A cat staring at a cucumber behind it, frozen in absolute horror and shock.',
  'A very old wrinkly bulldog in a rocking chair wearing a cardigan, grumpy at nothing.',
  'An otter floating on its back in a pool with sunglasses, sipping a juice box.',
  'A chameleon at a disco party accidentally turning every color at once.',
  'Five turtles balanced on top of each other, the bottom one deeply regretting everything.',
  'A horse photobombing a couple\'s romantic selfie with a ridiculous grin.',
  'Baby ducklings trying to climb a single stair step, total chaos, some falling backwards.',
  'A pelican attempting to swallow something way too large, completely bewildered.',
  'A koala aggressively hugging a tree while making direct eye contact, asserting dominance.',
  'A dramatic western movie standoff between two house cats in a suburban driveway.',
  'A tiny mouse at a fancy dinner table with a tucked napkin and silverware.',
  'A yellow parakeet with a surprised pikachu-style reaction, beak wide open in shock.',
  'A corgi with very short legs trying to jump over a tiny fence and barely making it.',
  'A seal balancing way too many fish on its nose, eyes crossed with concentration.',
];

// ── CAPTION CARDS (White Cards) ─────────────────────────────
// Organized by spice level: 1 = family-friendly, 2 = edgy, 3 = unhinged
const captionCards = {
  1: [
    // Social media / internet culture
    "When the WiFi goes out",
    "Me trying to adult",
    "My face when I realize it's Monday",
    "Waiting for the pizza delivery like...",
    "That awkward moment when...",
    "When you thought you muted yourself on Zoom",
    "My brain cells trying to work on a Friday",
    "The struggle is real",
    "Just five more minutes...",
    "When you accidentally like an old photo",
    "Trying to explain tech to my parents",
    "When the snack drawer is empty",
    "Is it Friday yet?",
    "When you hear the ice cream truck",
    "Trying to be productive after lunch",
    "When someone says 'we need to talk'",
    "Me pretending to understand",
    "When you see the bill",
    "What my teacher thinks I'm doing vs. reality",
    "When someone eats your labeled leftovers",
    "Trying to look natural in photos",
    "When the group project is due tomorrow",
    "My reaction to surprise plans",
    "When autocorrect strikes again",
    "POV: you forgot someone's name immediately",
    "When Mom uses your full name",
    "Trying to cook from a recipe for the first time",
    "That one friend who's always late",
    "When you find money in your old jacket",
    "Social media vs. reality",
    "When the elevator opens and it's full of people",
    "Running to catch the bus... and missing it",
    "Me after saying 'I'll start Monday'",
    "When the teacher picks you and you weren't listening",
    "POV: you're the only one who dressed up",
    "That look when someone takes the last slice",
    "Me googling my symptoms at 2 AM",
    "When the 'quick meeting' hits the 1-hour mark",
    "Waving back at someone who wasn't waving at you",
    "When your phone dies at 1% mid-text",
    "Me pretending to stretch so I can check the clock",
    "When you hear your name in someone else's conversation",
    "Trying to remember if you locked the door",
    "When the 'short cut' adds 30 extra minutes",
    "POV: your alarm didn't go off",
    "When you accidentally open the front camera",
    "Me in the group chat at 3 AM",
    "When the package says 'out for delivery'",
    "Telling yourself 'just one more episode'",
    "My pet judging my life choices",
    "When someone says 'Can I ask you something?'",
    "Me vs. assembling IKEA furniture",
    "When the song in your head turns out to be a bop",
    "That face when the food is too hot but too good to stop",
    "Walking past the same person 3 times in a grocery store",
    "When your charger only works at that one angle",
    "Me trying to sneak snacks into the theater",
    "When you accidentally send to the wrong chat",
    "POV: you parked and forgot where",
    "Nailed it. (Narrator: they did not nail it)",
  ],
  2: [
    // Edgy / snarky
    "That's what she said",
    "Trying to be subtle but failing spectacularly",
    "My therapist is going to hear about this",
    "Just a little bit of trauma, as a treat",
    "When you sent that text to the wrong person",
    "My search history at 3 AM",
    "Asking for a friend... who is definitely me",
    "When the red flags look like normal flags",
    "Trying to keep it together after one too many",
    "My dating life in a nutshell",
    "When you thought it was a compliment",
    "My body is a temple of questionable decisions",
    "When you're overthinking at 3 AM",
    "The morning after",
    "Pretty sure that's a felony",
    "Trying to flirt but you're just awkward",
    "I swear I'm a good person",
    "When your ex texts 'hey'",
    "My bank account judging me",
    "When they say 'let's just be friends'",
    "Me pretending everything is fine",
    "Sunday scaries hitting different",
    "When you realize you peaked in high school",
    "Corporate wants you to find the difference",
    "Toxic trait unlocked",
    "When someone replies 'k'",
    "Main character energy gone wrong",
    "My last brain cell at 2 AM",
    "When you ARE the drama",
    "Plot twist nobody asked for",
    "Gaslight, gatekeep, girlboss",
    "Live, laugh, lose it",
    "When the vibes are off",
    "Catch me outside energy",
    "When you accidentally overshare",
    "My toxic trait is thinking I can fix them",
    "Relationship status: complicated with my WiFi",
    "When your horoscope personally attacks you",
    "Forgot the meds this morning and it SHOWS",
    "When you stalk too deep and like a 2019 photo",
    "My emotional support energy drink",
    "One bad decision away from a great story",
    "When the 'no drama' person IS the drama",
    "Telling my therapist about my week and even they look concerned",
    "POV: you just saw your ex's new partner",
    "When your coping mechanism needs a coping mechanism",
    "I'm not arguing, I'm passionately explaining why I'm right",
    "When you realize you've become the person you judged",
    "My impulse purchases judging me from the corner",
    "POV: you're the group chat's content",
    "Trust issues? I call it pattern recognition",
    "My comfort show for the 47th time",
    "When you get called 'bestie' by someone you met twice",
    "Deleting the paragraph and sending 'lol ok'",
    "When you overhear gossip and it's about you",
    "My brain writing fanfic about things that'll never happen",
    "The audacity of this Monday",
    "When you say 'I'm fine' and your eye twitches",
    "Online shopping at 2 AM: 'I deserve this'",
    "When the 'seen' notification hits but no reply comes",
  ],
  3: [
    // Unhinged / chaotic
    "I've made a huge mistake",
    "My fight or flight chose 'freeze and stare blankly'",
    "The voices told me to do it",
    "This is fine. Everything is fine.",
    "Pretty sure I peaked in kindergarten",
    "When the existential dread hits at 2 PM on a Tuesday",
    "I talked to my houseplants today. They judged me.",
    "Just another Tuesday in the apocalypse",
    "My therapist just retired. Coincidence?",
    "Pretty sure I'm in a simulation and the devs stopped caring",
    "I regret nothing... yet",
    "My brain cells actively self-destructing",
    "The last brain cell holding it all together",
    "Welcome to my mental breakdown: the musical",
    "Get help. But make it aesthetic.",
    "Society when I'm in charge",
    "God creating me at 3 AM on a weekday",
    "Satan called. He wants his vibe back.",
    "Born to chill, forced to adult",
    "Sleep paralysis demon checking in",
    "When you dissociate mid-conversation",
    "Me gaslighting myself into thinking I'm fine",
    "Chaos goblin mode: ACTIVATED",
    "My obituary is going to be wild",
    "The intrusive thoughts won today",
    "This is my villain origin story",
    "Weaponized incompetence",
    "Feral behavior, but make it professional",
    "Screaming into the void on company time",
    "My comfort zone is a war zone",
    "Unhinged and thriving",
    "Emotionally unavailable but still here",
    "Rock bottom has a basement",
    "POV: you've given up but in a fun way",
    "Core memory: unlocked and traumatic",
    "Normal people scare me more than this does",
    "My survival instincts are purely decorative",
    "I contain multitudes and they're all tired",
    "The urge to simply vanish into the woods",
    "My red flags have red flags",
    "I'm not a threat, I'm a promise",
    "Just blacked out and bought a plane ticket",
    "Every day I stray further from sanity",
    "The demons are winning and honestly they've earned it",
    "Running on spite and expired energy drinks",
    "My personality is barely controlled chaos",
    "This timeline is the darkest one and I have proof",
    "I am both the problem and the solution",
    "Manifesting my downfall in HD",
    "My emotional range is 'fine' to 'feral'",
    "Living proof that natural selection gave up",
    "If I had a dollar for every red flag I ignored I could afford therapy",
    "I am one minor inconvenience away from becoming a cryptid",
    "The WiFi went out and I saw my family. They seem nice.",
    "POV: you are the cautionary tale",
    "I don't have a plan. I barely have a pulse.",
    "Accidentally became the family disappointment speedrun any%",
    "Normalize screaming into a pillow as a strategy",
    "My comfort zone left the chat",
    "Somebody come get me I'm in a food coma and I can't move",
  ],
};

export function buildMemeDeck(spiceLevel = 1) {
  // Collect caption cards for the given spice level and below
  let allCaptions = [];
  for (let lvl = 1; lvl <= spiceLevel; lvl++) {
    if (captionCards[lvl]) allCaptions = allCaptions.concat(captionCards[lvl]);
  }
  return {
    blackCards: [...memeCards],
    whiteCards: allCaptions,
  };
}
