// Meme Melee — Card Deck
// "Black cards" are meme images, "White cards" are caption cards
// Images are static files in client/public/images/meme-melee/
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const MEME_DIR = path.join(__dirname, '..', '..', '..', 'client', 'public', 'images', 'meme-melee');

// ── MEME IMAGE CARDS (Black Cards) ──────────────────────────
// Each has a category, imageUrl, alt text, and pick count
export const memeCards = [
  // ── Animals Being People ──
  { imageUrl: '/images/meme-melee/meme-01.png', alt: 'stressed pigeon in business suit', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-02.png', alt: 'surprised lion cub', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-04.png', alt: 'cool dog on beach', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-05.png', alt: 'cat demanding food at table', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-06.png', alt: 'superhero squirrel on acorn', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-07.png', alt: 'sloth running marathon', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-08.png', alt: 'ducks graduating', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-09.png', alt: 'giraffe hiding behind bush', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-10.png', alt: 'bear baking disaster', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-11.png', alt: 'hamster driving monster truck', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-12.png', alt: 'sheep doing yoga', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-14.png', alt: 'grumpy octopus king', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-15.png', alt: 'eagle dropping fry', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-17.png', alt: 'cat wizard casting spell', pick: 1, category: 'animals' },

  // ── Everyday Struggles ──
  { imageUrl: '/images/meme-melee/meme-03.png', alt: 'elderly person confused by phone', pick: 1, category: 'everyday' },
  { imageUrl: '/images/meme-melee/meme-16.png', alt: 'office workers in animal costumes', pick: 1, category: 'everyday' },
  { imageUrl: '/images/meme-melee/meme-18.png', alt: 'person failing to open jar', pick: 1, category: 'everyday' },
  { imageUrl: '/images/meme-melee/meme-19.png', alt: 'child drawing come to life', pick: 1, category: 'everyday' },
  { imageUrl: '/images/meme-melee/meme-20.png', alt: 'gnome backyard party', pick: 1, category: 'everyday' },

  // ── Weird Situations ──
  { imageUrl: '/images/meme-melee/meme-13.png', alt: 'alien tourist selfie', pick: 1, category: 'weird' },

  // ── Expansion Batch 21-40 ──
  { imageUrl: '/images/meme-melee/meme-21.png', alt: 'raccoon sneaking into movie theater', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-22.png', alt: 'golden retriever scientist at chalkboard', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-23.png', alt: 'penguin lost in desert', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-24.png', alt: 'cat caught on counter', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-25.png', alt: 'seagulls fighting over french fry', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-26.png', alt: 'chihuahua CEO in big chair', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-27.png', alt: 'meerkats doing synchronized exercise', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-28.png', alt: 'unimpressed fish in fishbowl', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-29.png', alt: 'rooster on fashion runway', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-30.png', alt: 'panda couch potato eating chips', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-31.png', alt: 'owl on laptop at 3 AM', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-32.png', alt: 'golden retriever lifeguard at empty pool', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-33.png', alt: 'two cats boxing', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-34.png', alt: 'duck with monocle reading newspaper', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-35.png', alt: 'pigeons in tactical SWAT gear', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-36.png', alt: 'tortoise with racing goggles', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-37.png', alt: 'philosophical frog on lily pad', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-38.png', alt: 'squirrel mid-air jump fail', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-39.png', alt: 'fluffy alpaca after salon blowout', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-40.png', alt: 'baby elephant in tiny kiddie pool', pick: 1, category: 'animals' },

  // ── Expansion Batch 41-60 ──
  { imageUrl: '/images/meme-melee/meme-41.png', alt: 'goat standing on car', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-42.png', alt: 'deer frozen mid-dance', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-43.png', alt: 'parrot on witness stand', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-44.png', alt: 'flamingo board meeting', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-45.png', alt: 'dog making derp face catching ball', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-46.png', alt: 'gorilla with birthday hat', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-47.png', alt: 'cat horrified by cucumber', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-48.png', alt: 'grumpy old bulldog in rocking chair', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-49.png', alt: 'otter floating with juice box', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-50.png', alt: 'chameleon at disco party', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-51.png', alt: 'five turtles stacked on each other', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-52.png', alt: 'horse photobombing romantic selfie', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-53.png', alt: 'baby ducklings climbing a stair step', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-54.png', alt: 'pelican trying to swallow something huge', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-55.png', alt: 'koala aggressively hugging tree', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-56.png', alt: 'two cats in western standoff', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-57.png', alt: 'tiny mouse at fancy dinner', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-58.png', alt: 'parakeet with shocked pikachu face', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-59.png', alt: 'corgi barely jumping tiny fence', pick: 1, category: 'animals' },
  { imageUrl: '/images/meme-melee/meme-60.png', alt: 'seal balancing too many fish', pick: 1, category: 'animals' },
  // ── Expansion Pack (Gemini-generated) ──
  { imageUrl: '/images/meme-melee/meme-61.png', alt: 'Flamingos tea party fancy', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-62.png', alt: 'Toddler fixes car banana', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-63.png', alt: 'Cat miserable birthday hat', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-64.png', alt: 'Baby goat plays fetch', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-65.png', alt: 'Pancake stack googly eyes', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-66.png', alt: 'Grumpy gnome squirrel argument', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-67.png', alt: 'Ducklings follow ladybug puddle', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-68.png', alt: 'Child remote plant vibrating', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-69.png', alt: 'Chinchillas sorting tiny mail', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-70.png', alt: 'Rabbit bakes tiny bread', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-71.png', alt: 'Eating giant pickle fancy', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-72.png', alt: 'Baby confused by feet', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-73.png', alt: 'Fox cub peeks bookshelf', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-74.png', alt: 'Gnomes play miniature golf', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-75.png', alt: 'Squirrel pays for nuts', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-76.png', alt: 'Defeated by fitted sheet', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-77.png', alt: 'Child presents mud pie', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-78.png', alt: 'Sleepy owl reading glasses', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-79.png', alt: 'Toaster sad burnt toast', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-80.png', alt: 'Raccoons build sandcastle', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-81.png', alt: 'Frog king bottle cap', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-82.png', alt: 'Squirrel with acorn trophy', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-83.png', alt: 'Struggling child-proof bottle', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-84.png', alt: 'Kids intense staring contest', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-85.png', alt: 'Hedgehog giant marshmallow', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-86.png', alt: 'Washing machine overflowing bubbles', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-87.png', alt: 'Swans synchronized swimming', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-88.png', alt: 'Sad balloon deflated cake', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-89.png', alt: 'Toddler helps clean dirt', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-90.png', alt: 'Pigeons examine dropped fry', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-91.png', alt: 'Person walks into glass', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-92.png', alt: 'Gnome confused smart device', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-93.png', alt: 'Rooster presents breakfast', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-94.png', alt: 'Child hides crayon drawing', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-95.png', alt: 'Sloth reluctantly birthday', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-96.png', alt: 'Traffic cone deserted beach', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-97.png', alt: 'Prairie dogs serious meeting', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-98.png', alt: 'Spinach selfie struggle', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-99.png', alt: 'Child teaches goldfish read', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-100.png', alt: 'Mouse pushes cheese skateboard', pick: 1, category: 'generated', spice: 1 },
  { imageUrl: '/images/meme-melee/meme-101.png', alt: 'Awkward date birthday song', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-102.png', alt: 'Passive aggressive office memo', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-103.png', alt: 'Parallel parking date disaster', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-104.png', alt: 'Home office hangover struggle', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-105.png', alt: 'Toilet paper shoe embarrassment', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-106.png', alt: 'Boring meeting phone browsing', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-107.png', alt: 'Empty fridge life choices', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-108.png', alt: 'Awkward dating app DM', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-109.png', alt: 'Flat pack furniture frustration', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-110.png', alt: 'Horrified credit card bill', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-111.png', alt: 'Staged candid selfie travel', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-112.png', alt: 'Out of order coffee machine', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-113.png', alt: 'Silent dirty dish argument', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-114.png', alt: 'Muted mic video call fail', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-115.png', alt: 'Awkward date skill showoff', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-116.png', alt: 'Stealth office nap desk', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-117.png', alt: 'Gourmet meal processed ingredients', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-118.png', alt: 'Pretending phone party avoidance', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-119.png', alt: 'Duct tape faucet repair', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-120.png', alt: 'Obvious surprise gift reaction', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-121.png', alt: 'No signal phone desperation', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-122.png', alt: 'Accidentally liked ex post', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-123.png', alt: 'Pet child video call interruption', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-124.png', alt: 'Microwave gourmet bewildered', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-125.png', alt: 'Covert date social media check', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-126.png', alt: 'Oversized best boss mug', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-127.png', alt: 'Secret fly check crowded', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-128.png', alt: 'Pet love partner ignored', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-129.png', alt: 'Printer jam angry stare', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-130.png', alt: 'Jar of pickles impossible', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-131.png', alt: 'Wrong group chat typo', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-132.png', alt: 'Ironed wrinkles into shirt', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-133.png', alt: 'Confused by corporate jargon', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-134.png', alt: 'Swiped left dream match', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-135.png', alt: 'Awkward wedding dance moves', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-136.png', alt: 'Flimsy tent windy struggle', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-137.png', alt: 'Yelling at smart speaker', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-138.png', alt: 'First time cooking chaos', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-139.png', alt: 'Guilty snack hoarder office', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-140.png', alt: 'Uncomfortable public affection', pick: 1, category: 'generated', spice: 2 },
  { imageUrl: '/images/meme-melee/meme-141.png', alt: 'Rubber duck vast stormy ocean', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-142.png', alt: 'Skeleton sad birthday cake', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-143.png', alt: 'Receipt existential dread', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-144.png', alt: 'Giant rabbit creepy window', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-145.png', alt: 'Fishbowl floating in space', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-146.png', alt: 'Underwater business meeting', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-147.png', alt: 'Office cubicle maze escape', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-148.png', alt: 'Plant suffocates self-help', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-149.png', alt: 'Smiling mannequins observe street', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-150.png', alt: 'Traffic light empty desert', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-151.png', alt: 'Hot dog bun floats to space', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-152.png', alt: 'Pigeons protest empty feeder', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-153.png', alt: 'Elevator endless commute', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-154.png', alt: 'Giant sock puppet stares TV', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-155.png', alt: 'Grumpy cloud sad rain', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-156.png', alt: 'Eagle sorts recycling facility', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-157.png', alt: 'Gnomes tiny seance candle', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-158.png', alt: 'Buffering screen existential crisis', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-159.png', alt: 'Business fly orders coffee', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-160.png', alt: 'Upside down tree roots sky', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-161.png', alt: 'Cat drives sports car bored', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-162.png', alt: 'Lonely sock deserted island', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-163.png', alt: 'VHS life regret montage', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-164.png', alt: 'Chimp butler severed hand', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-165.png', alt: 'Whale swims through clouds', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-166.png', alt: 'Sentient carts escape lot', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-167.png', alt: 'Kick me sign gravestone', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-168.png', alt: 'Stock photo existential loop', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-169.png', alt: 'Goblin reads bedtime story', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-170.png', alt: 'Fish flock in sky sunset', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-171.png', alt: 'Giant broccoli house roof', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-172.png', alt: 'Headless doll swing set', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-173.png', alt: 'No reflection black puddle', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-174.png', alt: 'Giant googly eyes stall', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-175.png', alt: 'Waterfall flows upwards clouds', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-176.png', alt: 'Gnomes chess foggy forest', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-177.png', alt: 'Giant candle tiny cupcake', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-178.png', alt: 'Waiting room stuck clock', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-179.png', alt: 'Flamingos chase mailman', pick: 1, category: 'generated', spice: 3 },
  { imageUrl: '/images/meme-melee/meme-180.png', alt: 'Hand from washing machine', pick: 1, category: 'generated', spice: 3 },
];

// Image generation prompts — used by generate-memes.js to create meme images
// Index matches meme-XX.png numbering
export const memePrompts = [
  'A highly stressed pigeon wearing a tiny business suit, frantically typing on a laptop with multiple overflowing coffee cups, surrounded by crumpled papers. Photorealistic meme-worthy style, dramatic lighting.',
  'A majestic lion cub making an extremely surprised face, eyes wide, mouth open in a perfect O of shock. Close-up portrait, viral meme style.',
  'An elderly person holding a smartphone upside down with a look of utter confusion and mild panic, wearing reading glasses on their forehead. Candid photo style.',
  'A dog wearing oversized sunglasses and a Hawaiian shirt, sipping a tiny cocktail with a straw, utterly relaxed on a miniature beach towel. Vibrant social media colors.',
  'A cat sitting at a dinner table with a knife and fork, staring intently and very displeased at an empty plate, demanding food with its eyes. Renaissance painting style.',
  'A squirrel in a flowing superhero cape, striking a dramatic pose on top of a giant acorn, looking overly confident. Action movie poster style.',
  'A very tired-looking sloth attempting to run a marathon, barely moving, dripping sweat with existential dread. Sports photography style.',
  'A group of ducks in single-file line wearing tiny graduation caps with scholarly expressions, marching towards a library.',
  'A bewildered giraffe trying to hide behind a small garden bush, with most of its neck visible, looking embarrassed.',
  'A bear in a chef hat attempting to bake, kitchen in total disaster: flour explosions, burnt pans, bewildered despair.',
  'A tiny hamster driving a monster truck through a miniature obstacle course made of household items, intensely focused.',
  'A very fluffy sheep attempting advanced yoga, tangled up, looking perplexed and stuck.',
  'An alien tourist with oversized eyes taking a selfie in front of a mundane fire hydrant, absolutely thrilled.',
  'A grumpy octopus wearing a tiny crooked crown, on a seashell throne, immensely annoyed by its subjects.',
  'A majestic eagle dramatically dropping a single french fry from its talons, looking utterly distraught.',
  'Office workers in ridiculous animal costumes having a very serious corporate boardroom meeting.',
  'A cat wearing a sparkling wizard hat casting a spell with an outstretched paw, surrounded by magical glow.',
  'A person dramatically failing to open a jar of pickles, sweat and defeat. Dramatic close-up.',
  'A child\'s crayon drawing of a monster brought to life, confused and embarrassed to exist. Mixed media.',
  'Garden gnomes throwing a wild tiny backyard party with disco lights and miniature boombox.',
  // 21-40: Expansion batch
  'A raccoon in a trench coat trying to sneak into a movie theater, looking extremely suspicious.',
  'A very confused golden retriever wearing a lab coat, staring at a chalkboard full of complex equations.',
  'A penguin in a hawaiian shirt looking lost in a desert, holding an upside-down map.',
  'A cat caught mid-crime standing on a kitchen counter, frozen, staring directly at the camera with wide eyes.',
  'Two seagulls aggressively fighting over a single french fry on a boardwalk, dramatic action shot.',
  'A very small chihuahua sitting in an enormous armchair at a boardroom table, looking like a tiny CEO.',
  'A group of meerkats in matching track suits doing synchronized exercise, one clearly not keeping up.',
  'A dramatic close-up of a fish in a fishbowl making an unimpressed face at a terrible magic trick.',
  'A confident rooster strutting down a fashion runway with dramatic lighting and a feathery outfit.',
  'A panda bear sitting on a couch eating chips, absolutely refusing to move, extreme couch-potato energy.',
  'An owl wearing reading glasses, hunched over a tiny laptop at 3 AM, looking exhausted and caffeinated.',
  'A golden retriever in a lifeguard outfit sitting in a tall chair, staring intensely at an empty pool.',
  'Two cats in boxing gloves facing off in a tiny boxing ring, one terrified, the other overconfident.',
  'A duck wearing a tiny monocle and top hat, reading a newspaper at a cafe, looking distinguished.',
  'A group of pigeons in tactical gear, lined up like a SWAT team, looking overly serious.',
  'A tortoise wearing tiny racing goggles at a starting line, looking extremely determined.',
  'A frog sitting on a lily pad in a philosophical thinking pose, tiny chin on hand.',
  'A squirrel having a dramatic mid-air jump fail between two branches, face frozen in panic.',
  'A very fluffy alpaca at a hair salon, looking fabulous after a dramatic blowout.',
  'A baby elephant trying to fit into a kiddie pool way too small for it, splashing everywhere.',
  // 41-60: More expansion
  'A goat standing on top of a car in a parking lot, looking like it owns the place.',
  'A deer caught in headlights but literally frozen mid-dance pose.',
  'A parrot in a courtroom at the witness stand, looking like it is about to snitch.',
  'A group of flamingos standing in a circle like a very important board meeting.',
  'A dog trying to catch a ball but making the most ridiculous derp face mid-jump.',
  'A gorilla wearing a tiny birthday hat, blowing out candles, looking mildly annoyed.',
  'A cat staring at a cucumber behind it, frozen in absolute horror and shock.',
  'A very old wrinkly bulldog in a rocking chair wearing a cardigan, grumpy at nothing.',
  'An otter floating on its back in a pool with sunglasses, sipping a juice box.',
  'A chameleon at a disco party accidentally turning every color at once.',
  'Five turtles balanced on top of each other, the bottom one deeply regretting everything.',
  'A horse photobombing a couple\'s romantic selfie with a ridiculous grin.',
  'Baby ducklings trying to climb a single stair step, total chaos, some falling backwards.',
  'A pelican attempting to swallow something way too large, completely bewildered.',
  'A koala aggressively hugging a tree while making direct eye contact, asserting dominance.',
  'A dramatic western movie standoff between two house cats in a suburban driveway.',
  'A tiny mouse at a fancy dinner table with a tucked napkin and silverware.',
  'A yellow parakeet with a surprised pikachu-style reaction, beak wide open in shock.',
  'A corgi with very short legs trying to jump over a tiny fence and barely making it.',
  'A seal balancing way too many fish on its nose, eyes crossed with concentration.',
  // ── Expansion Pack prompts (61-180) ──
  "A group of elegant flamingos gathered around a small, ornate table, delicately sipping from tiny teacups with their long necks, feathers perfectly preened. Photorealistic, soft lighting.",
  "A chubby toddler with a determined expression, wearing a messy bib, deeply focused on trying to 'repair' a broken toy car by repeatedly tapping it with a ripe yellow banana. Bright, natural lighting, high detail.",
  "A fluffy cat, forced into a tiny, colorful party hat, sits on a pristine cake, staring directly at the camera with an expression of profound existential dread and mild indignation. Photorealistic, slightly humorous.",
  "A tiny, fluffy baby goat, standing in a lush green field, comically trying to pick up and carry a tree branch that is significantly larger and longer than itself. Bright, cheerful, and photorealistic.",
  "A perfectly golden stack of pancakes, topped with a pat of butter, featuring large, comically surprised googly eyes as a stream of maple syrup pours down its side. Bright, warm lighting, food photography style.",
  "A traditional ceramic garden gnome with a perpetually grumpy expression, standing in a flower bed, angrily shaking a tiny fist at a quick, cheeky squirrel who is raiding a bird feeder. Photorealistic, slightly humorous.",
  "A perfectly straight line of fluffy yellow baby ducklings, walking one behind the other, intently following a small red ladybug as it crawls across the surface of a shallow puddle. Bright, charming, photorealistic.",
  "A young child with wide, confused eyes, clutching a TV remote control, staring intently at a potted houseplant that is visibly vibrating and shaking on a table beside them. Interior, soft light, photorealistic.",
  "A detailed miniature post office interior, where several fluffy chinchillas, wearing tiny postman hats, are diligently sorting tiny letters into small mail slots. Photorealistic, highly detailed, whimsical.",
  "A fluffy rabbit, wearing a white baker's apron and chef's hat, intently kneading a small ball of dough on a miniature floured workbench in a charming tiny bakery setting. Photorealistic, warm lighting.",
  "A person in formal attire, sitting at an elegant restaurant table with white tablecloths, attempting to subtly and discreetly eat an comically oversized dill pickle with a look of mild embarrassment. Photorealistic, humorous.",
  "A very young baby, lying on a soft blanket, looking down at its own feet with an expression of profound confusion and wonder, as if seeing them for the first time. Bright, wholesome, photorealistic.",
  "A cute, fluffy fox cub with large ears, playfully peeking its head out from behind a warmly lit, overflowing bookshelf in a cozy living room, looking directly at the camera. Photorealistic, charming.",
  "A whimsical scene in a backyard with several garden gnomes, holding tiny golf clubs, intently playing miniature golf on a perfectly manicured lawn, complete with tiny windmills and obstacles. Photorealistic, charming.",
  "A sophisticated squirrel, wearing a tiny fedora, standing at a miniature grocery store checkout counter, holding a tiny wallet and looking expectantly at a tiny cashier. Photorealistic, humorous.",
  "A person standing in a brightly lit laundry room, completely defeated and tangled in a large, unmanageable fitted sheet, looking utterly exasperated with their folding attempt. Photorealistic, relatable.",
  "A beaming child, covered in dirt, holding out a mud pie on a pristine porcelain plate with an expression of immense pride, offering it to an amused parent. Outdoor setting, bright, photorealistic.",
  "A fluffy owl with its eyes barely open, wearing a tiny pair of reading glasses perched on its beak, slowly dozing off while sitting on a towering stack of open academic books. Photorealistic, cozy.",
  "A slightly singed, anthropomorphic toaster oven with drawn-on sad eyes, looking down at a single, completely burnt piece of toast lying on a plate in front of it. Kitchen counter, humorous, photorealistic.",
  "A family of raccoons, some wearing tiny beach hats, diligently working together to construct a surprisingly elaborate sandcastle on a busy, sunny beach, looking intensely focused. Photorealistic, charming.",
  "A small green frog, wearing a tiny, ill-fitting golden crown on its head, sitting by a puddle and intently inspecting a discarded bottle cap with wide eyes. Outdoor, natural lighting, photorealistic.",
  "A muscular-looking squirrel, flexing its tiny biceps, proudly holding up an impossibly large acorn above its head like a bodybuilding champion receiving a trophy. Forest background, humorous, photorealistic.",
  "A person with a look of intense frustration and concentration, gritting their teeth, exerting maximum effort to open a seemingly impenetrable child-proof medicine bottle. Close-up, photorealistic.",
  "Three young children in a school playground, seated face-to-face, locked in an incredibly intense and dramatic staring contest, eyes wide open and unblinking, serious expressions. Outdoor, bright, photorealistic.",
  "A small hedgehog, walking carefully across a patch of grass, struggling to carry an impossibly large, fluffy white marshmallow in its tiny paws. Outdoor, charming, photorealistic.",
  "A modern washing machine, its door slightly ajar, comically overflowing with an enormous amount of soap bubbles, while a person stands beside it with a look of utter disbelief and exasperation. Kitchen/laundry room, photorealistic.",
  "A group of majestic white swans, gracefully performing a perfectly synchronized swimming routine in a serene pond, their movements fluid and elegant, creating ripples in the water. Outdoor, beautiful, photorealistic.",
  "A forlorn, deflated birthday balloon, its string tangled messily around a half-eaten, slightly smudged birthday cake on a table, conveying a sense of post-party sadness. Soft lighting, photorealistic.",
  "A very young toddler, wearing overalls, with a look of intense concentration, pushing a miniature toy broom into a surprisingly large pile of dirt on a clean kitchen floor, creating more mess. Bright, humorous, photorealistic.",
  "A congregation of several pigeons, all gathered around a single, perfectly golden dropped french fry on a sidewalk, peering at it with an intense, scientific curiosity. Urban setting, photorealistic, humorous.",
  "A person with a slightly bewildered and dazed expression, having just walked face-first into a perfectly clean, clear glass door, one hand touching their forehead in mild pain. Office or modern building, photorealistic.",
  "A traditional garden gnome, seated on a modern kitchen counter, looking with wide, confused eyes at a sleek, glowing smart home speaker device, as if trying to understand its purpose. Photorealistic, humorous.",
  "A majestic rooster, standing proudly in a rustic kitchen, wearing a pristine chef's hat, gesturing with a wing towards a beautifully laid-out breakfast spread of eggs and bacon. Warm lighting, photorealistic, charming.",
  "A young child with a mischievous grin, attempting to very subtly 'hide' a colorful, scribbled crayon drawing on a refrigerator by carefully placing a magnet directly over the most incriminating part. Kitchen, bright, photorealistic.",
  "A slow-moving sloth, wearing a tiny, crooked party hat, very, very slowly and reluctantly blowing out the single candle on a small birthday cake, looking utterly unenthusiastic. Photorealistic, humorous.",
  "A bright orange traffic cone, looking out of place and slightly melancholic, sitting alone on a wide, deserted sandy beach as the sun sets in the background, casting long shadows. Serene, unexpected, photorealistic.",
  "Several prairie dogs, standing upright in a close circular huddle, appearing to be engaged in a very serious and hushed conversation, their tiny paws gesturing subtly. Open grassland, bright, photorealistic.",
  "A person smiling for a selfie, but with one finger subtly trying to dislodge a visible piece of spinach from their front teeth, eyes wide with mild panic. Close-up, photorealistic, humorous.",
  "A young child, kneeling beside a fishbowl, holding up a colorful picture book to a pet goldfish, pointing at the pages with a very serious and encouraging expression. Home interior, wholesome, photorealistic.",
  "A small, determined mouse, wearing a tiny backpack, meticulously pushing an impossibly large block of cheese on a miniature skateboard across a clean kitchen floor. Photorealistic, charming, whimsical.",
  "A couple on a first date, seated at a restaurant table, the man leaning in with a forced smile attempting small talk, while in the background, a loud waiter vigorously sings 'Happy Birthday' to another table, making eye contact. Photorealistic, slightly cringey.",
  "A close-up of a brightly colored, overly polite yet clearly passive-aggressive office memo tacked to a bustling office bulletin board, with specific phrases underlined, obviously targeting an individual. Photorealistic, office environment.",
  "A person in the driver's seat, grimacing in concentration as they attempt a difficult parallel park, while their date in the passenger seat subtly braces for impact, wide-eyed with fear and regret. Street scene, night, photorealistic.",
  "A dishevelled person, wearing sunglasses indoors, hunched over a laptop at a cluttered home office desk, surrounded by empty coffee mugs, painkiller packets, and a half-eaten greasy breakfast. Morning light, photorealistic, relatable.",
  "A person confidently walking out of a public restroom, oblivious to the long stream of toilet paper trailing elegantly from their shoe, while passersby subtly try to suppress smiles. Public hallway, photorealistic.",
  "A corporate meeting room with a large table, where several professionals are seated, appearing to pay attention to a speaker, but with their hands discreetly below the table, illuminated by the glow of their smartphones. Photorealistic, office environment.",
  "A person with a look of existential despair, standing in a dimly lit kitchen, staring into a completely empty, pristine refrigerator, reflecting on poor grocery decisions. Photorealistic, relatable.",
  "A close-up of a smartphone screen showing a dating app, displaying a very cringeworthy, overly confident, and poorly punctuated opening message being typed by a person's thumbs in the foreground. Photorealistic, common scenario.",
  "A frustrated person, sitting on the floor amidst a chaotic pile of unfinished flat-pack furniture pieces, confusing instruction manuals, and scattered tools, with a single screw held up in bewilderment. Home interior, photorealistic.",
  "A person seated at a kitchen table, eyes wide with horror, holding a large credit card bill, one hand dramatically clutching their forehead in utter disbelief at the total amount. Home interior, dramatic lighting, photorealistic.",
  "A person carefully posing in a picturesque exotic location (e.g., in front of a famous landmark), holding their phone to take a 'candid' selfie, clearly directing their own relaxed expression. Bright, travel photography style, photorealistic.",
  "A broken coffee machine with a hastily written 'OUT OF ORDER' sign taped to it, surrounded by a small queue of tired, glassy-eyed office workers looking like desperate zombies in need of caffeine. Office kitchen, photorealistic.",
  "A couple standing stiffly in a modern kitchen, backs turned slightly to each other, both staring intensely at a single dirty dish in an otherwise spotless sink, radiating passive-aggressive tension. Photorealistic, domestic.",
  "A person on a video conference call, mid-sentence with an animated expression, suddenly realizing their microphone has been muted the entire time, their eyes widening in mortification. Laptop screen view, photorealistic.",
  "A person, trying too hard to impress their date, awkwardly attempting to juggle two apples in a casual restaurant setting, one apple already wobbling precariously, while their date looks unimpressed. Photorealistic, slightly cringey.",
  "An office employee, slumped down in their chair, clearly asleep, with their head mostly obscured by a large computer monitor and a strategically placed potted plant, hoping to go unnoticed. Photorealistic, office cube.",
  "A person, looking earnest, carefully following a complex recipe book for a 'gourmet meal,' but the ingredients laid out on the counter are distinctly from processed, packaged foods, like instant ramen and cheese slices. Kitchen, humorous, photorealistic.",
  "A single person standing awkwardly alone at a bustling party, their face illuminated by the glow of their smartphone, pretending to be deeply engrossed in a text to avoid eye contact or conversation. Dark, party lighting, photorealistic.",
  "A person with a determined but slightly desperate expression, tightly wrapping several layers of silver duct tape around a actively dripping kitchen faucet, clearly hoping for a miracle. Kitchen sink, photorealistic.",
  "One partner holding a clumsily wrapped, very obviously shaped gift (e.g., a clearly visible guitar neck sticking out), while the other partner feigns an expression of utter astonishment and delight. Living room, humorous, photorealistic.",
  "A person standing in a beautiful, remote natural landscape (e.g., top of a mountain), holding their smartphone high above their head, desperately waving it around in search of a non-existent cell signal. Outdoor, scenic, humorous.",
  "A close-up of a smartphone screen showing a person's thumb hovering over the 'unlike' button of a very old, embarrassing social media post belonging to their crush's ex, their face in the reflection wide with panic. Screen glow, photorealistic.",
  "A corporate video call screen showing a professional speaking, while directly behind them, a cat is gracefully knocking over a stack of books, or a child is comically running past in a superhero cape. Screen capture style, humorous, photorealistic.",
  "A person standing in front of an open microwave, staring with utter bewilderment and disappointment at a strangely textured, barely edible-looking meal on a plate inside it. Kitchen, soft lighting, photorealistic.",
  "A person seated at a dinner table, making eye contact and smiling at their date, but their free hand is subtly hidden below the table, illuminated by a smartphone screen displaying their date's social media profile. Restaurant setting, photorealistic.",
  "An office employee, beaming with self-satisfaction, carrying a comically oversized ceramic mug that boldly declares 'WORLD'S BEST BOSS' into a busy office, walking past confused coworkers. Office environment, humorous, photorealistic.",
  "A person in a crowded public space (e.g., subway, shopping mall), discreetly attempting to check if their pants fly is open, using a series of subtle, awkward movements while trying to appear casual. Photorealistic, urban.",
  "A person dotingly stroking their pet (e.g., cat, dog) with intense affection, making cooing noises, while their human partner sits just a few feet away, looking visibly miffed and ignored. Cozy living room, photorealistic, humorous.",
  "A close-up of a paper tray of a modern office printer, with several crumpled pieces of paper jammed inside, while a frustrated person's face, contorted in an angry stare, looms in the background. Office setting, photorealistic.",
  "A person with a red face and bulging neck veins, struggling with all their might to twist open a stubborn jar of pickles, the lid completely unyielding to their extreme efforts. Kitchen, close-up, photorealistic.",
  "A close-up of a smartphone screen showing a text message with an obvious, embarrassing typo sent to a group chat, with a person's finger hovering over the delete button, eyes wide in horror. Screen glow, photorealistic.",
  "A person looking bewildered and defeated, holding up a freshly ironed shirt that now has an even more complex and permanent pattern of wrinkles pressed into it, clearly worse than before. Laundry room, photorealistic.",
  "An office employee, leaning against a cubicle wall, staring at a brightly colored 'motivational' corporate poster filled with buzzwords and corporate jargon, their face a mask of utter confusion and bewilderment. Office setting, photorealistic.",
  "A close-up of a smartphone screen showing a dating app profile, with a person's hand frozen in mid-air, eyes wide with horror as they realize they just accidentally swiped left on their perfect match. Screen glow, photorealistic.",
  "A person on a crowded wedding dance floor, attempting to execute 'cool' dance moves with extreme confidence, but their movements are completely out of sync, awkward, and drawing stares. Wedding reception, photorealistic.",
  "A person in an outdoor setting (e.g., campsite), battling a strong gust of wind, desperately trying to assemble a flimsy tent that is flapping and collapsing around them, their face a picture of pure frustration. Outdoor, humorous, photorealistic.",
  "A person standing in a modern living room, yelling loudly and exasperatedly at a sleek smart speaker, which has just responded with a completely irrelevant answer to a very simple command. Home interior, photorealistic.",
  "A person in a chaotic kitchen, covered in flour and various food splatters, holding a complex recipe book with a look of overwhelmed determination, surrounded by dirty pots, pans, and spilled ingredients. Home kitchen, photorealistic.",
  "An office employee, caught in the act, subtly stuffing their pockets with free office snacks (e.g., mini candy bars, bags of chips), their eyes wide with guilt as a coworker observes them. Office breakroom, photorealistic, humorous.",
  "A single person sitting on a park bench or in a cafe, trying to subtly avert their gaze, looking visibly uncomfortable as an overly affectionate couple next to them engages in an intense public display of affection. Outdoor/cafe, photorealistic.",
  "A single, bright yellow rubber duck, looking comically small, floating precariously on enormous, dark, turbulent waves in a vast and desolate stormy ocean under a dramatic sky. Surreal, photorealistic, cinematic.",
  "A fully articulated skeleton, wearing a tiny, brightly colored party hat, sitting alone at a small, dimly lit table, staring at a single, untouched slice of birthday cake with a forlorn expression. Dark humor, photorealistic.",
  "A person staring blankly at a receipt for a seemingly insignificant purchase, contemplating the meaning of life. Their expression conveys profound existential dread, questioning fundamental existence. Close-up, soft, introspective lighting, photorealistic.",
  "A comically giant, slightly dishevelled, fluffy white rabbit with glowing red eyes, slowly rising into view outside a child's bedroom window at night, its immense size filling the frame. Dark, eerie, yet absurdly funny, photorealistic.",
  "A spherical glass fishbowl, containing a single curious goldfish, inexplicably floating through the vacuum of outer space, with the blue and white marble of Earth visible in the background. Surreal, high contrast, photorealistic.",
  "A group of stern-faced businessmen in full suits and ties, seated around an opulent boardroom table, completely submerged underwater, breathing from tiny, hidden scuba tanks, with fish swimming past. Surreal, photorealistic.",
  "A person, disheveled and frantic, desperately trying to navigate an endless, labyrinthine maze constructed entirely from identical grey office cubicle walls, their face a mask of growing despair. Overhead shot, high contrast, photorealistic.",
  "A small, once vibrant houseplant, visibly wilting and dying, almost completely buried under an impossibly tall, precariously balanced stack of brightly colored self-help books. Gloomy lighting, indoor, photorealistic.",
  "A person walking down a deserted city street at night, completely unaware of a silent, unmoving flock of identical mannequins, all with wide, unsettlingly fixed smiles, observing them from doorways and windows. Eerie, photorealistic.",
  "A single, glowing green traffic light, standing inexplicably upright in the middle of a sprawling, empty desert landscape under a starry night sky, with no roads or signs around. Surreal, stark, cinematic, photorealistic.",
  "A perfectly golden, empty hot dog bun, strangely buoyant, slowly ascending into the dark expanse of outer space, tied to a cluster of tiny, brightly colored party balloons. Whimsical, surreal, photorealistic.",
  "A small group of disgruntled pigeons, wearing tiny, hand-drawn protest signs (e.g., 'SEED NOW!'), angrily picketing around an empty bird feeder in a suburban backyard. Humorous, photorealistic, slightly absurd.",
  "A person with a defeated and weary expression, standing alone in a sterile office elevator, looking out at the closing doors as it endlessly ascends and descends, devoid of floor buttons or escape. Photorealistic, unsettling.",
  "A comically large, crudely made human-sized sock puppet with button eyes, sitting perfectly still and upright in a cozy living room armchair, silently staring at the back of a person watching TV, unseen by them. Eerie, humorous, photorealistic.",
  "A bright, sunny street scene, but directly overhead, a single enormous cloud, clearly shaped like a grumpy human face, is raining down tiny, perfectly formed sad tears onto the pavement below. Surreal, vivid, photorealistic.",
  "A majestic bald eagle, wearing tiny safety glasses, standing upright in a sparkling, futuristic recycling facility, meticulously sorting plastic bottles from paper with its beak. Surreal, humorous, photorealistic.",
  "A circle of traditional garden gnomes, their faces unusually serious, gathered around a small, flickering candle in a dimly lit garden shed, holding hands for a miniature seance. Eerie, humorous, photorealistic.",
  "A close-up of a computer monitor displaying a perpetually spinning, buffering loading icon, with a person's reflection in the screen, their face contorted in a silent scream of existential crisis. Dim room, photorealistic, unsettling.",
  "A comically oversized, anthropomorphic housefly, wearing a perfectly tailored miniature business suit and tie, standing at the counter of a bustling urban coffee shop, attempting to order a latte. Absurd, humorous, photorealistic.",
  "A large, mature tree, growing entirely upside down in a lush green field, its gnarled roots reaching towards the sky like branches, while its leafy crown is buried deep beneath the earth. Surreal, vibrant, photorealistic.",
  "A fluffy cat, wearing a tiny leather jacket and sunglasses, behind the wheel of a miniature, souped-up sports car, driving through a suburban neighborhood with an expression of profound boredom. Humorous, photorealistic, action shot.",
  "A single, forlorn white sock, looking weathered and abandoned, sitting upright on a small, deserted tropical island beach, gazing wistfully out at the vast, empty ocean. Humorous, slightly poignant, photorealistic.",
  "A person with a look of profound regret and despair, watching an old, grainy VHS tape playing on a vintage TV, which shows a montage of their own past life choices, clearly leading to bad outcomes. Dim lighting, nostalgic yet unsettling, photorealistic.",
  "A perfectly groomed chimpanzee, wearing a neat butler's uniform, standing in a dimly lit, opulent mansion, holding a silver platter on which rests a realistic, but clearly prop, severed human hand. Darkly humorous, unsettling, photorealistic.",
  "A colossal, majestic humpback whale, with its barnacled body gleaming, swimming effortlessly through a sea of fluffy white clouds high above a sprawling, sunlit metropolis. Surreal, breathtaking, photorealistic.",
  "Several shopping carts, each with drawn-on angry or determined faces, silently and slowly moving in unison across a dark, empty supermarket parking lot, attempting a coordinated escape. Eerie, humorous, photorealistic.",
  "A close-up of a very old, moss-covered gravestone in a gloomy cemetery, with a comically oversized, brightly colored 'KICK ME' sign clumsily taped to its back. Dark humor, atmospheric, photorealistic.",
  "A person's face, tired and glazed over, illuminated by a computer screen, on which an endless, repeating loop of generic, cheerful stock photography images (e.g., people laughing at salad) plays relentlessly. Office setting, photorealistic.",
  "A small, grotesque yet oddly charming goblin, wearing miniature striped pajamas and a nightcap, sitting on the edge of a child's bed, holding a picture book and reading a bedtime story with a surprisingly gentle expression. Eerie, whimsical, photorealistic.",
  "A vibrant sunset sky, where instead of birds, a large flock of shimmering fish (e.g., mackerel, tuna) are gracefully flying in formation, silhouetted against the colorful horizon. Surreal, beautiful, photorealistic.",
  "A normal suburban house, but from its roof, a colossal, impossibly large broccoli stalk has violently erupted, tearing through the shingles and reaching towards the sky. Surreal, humorous, photorealistic.",
  "A desolate backyard swing set, with a worn, headless doll sitting perfectly upright in one of the swings, gently swaying back and forth in a faint breeze, its empty neck staring forward. Eerie, melancholic, photorealistic.",
  "A person kneeling by a perfectly still, inky black puddle on a dark street, staring intently at its surface, trying to find their reflection, but it shows absolutely nothing, just endless blackness. Dark, unsettling, photorealistic.",
  "A person sitting on a toilet in a public bathroom stall, looking up with wide, terrified eyes at a pair of comically oversized, disembodied googly eyes slowly peering over the top of the stall door. Humorous, jump scare, photorealistic.",
  "A majestic waterfall, but instead of falling downwards, its water is powerfully flowing upwards into the sky, defying gravity, culminating in a turbulent mass of white clouds. Surreal, breathtaking, photorealistic.",
  "A circle of traditional garden gnomes, their faces grim and concentrated, playing a serious chess tournament on a miniature chessboard in a mystical, foggy forest, surrounded by moss and tiny mushrooms. Whimsical, eerie, photorealistic.",
  "A comically oversized, brightly lit birthday candle, casting long shadows, stuck into a single, very small and lonely cupcake, sitting on a pristine white pedestal in the center of a vast, empty, dimly lit room. Humorous, melancholic, photorealistic.",
  "A person sitting alone in a drab, sterile waiting room, staring with a look of profound despair at a wall clock whose hands are visibly stuck, perpetually displaying the same unmoving time. Fluorescent lighting, unsettling, photorealistic.",
  "A terrified mailman, dropping his mailbag, running frantically down a suburban street, being fiercely pursued by an aggressive flock of bright pink plastic garden flamingos that have inexplicably come to life. Absurd, humorous, photorealistic.",
  "A person's bare hand, reaching out from the open door of a spinning washing machine, perfectly holding up a freshly laundered, impeccably folded white shirt against the swirling suds inside. Surreal, clean, photorealistic.",
];

// ── CAPTION CARDS (White Cards) ─────────────────────────────
// Organized by spice level: 1 = family-friendly, 2 = edgy, 3 = unhinged
const captionCards = {
  1: [
    // Social media / internet culture
    "When the WiFi goes out",
    "Me trying to adult",
    "My face when I realize it's Monday",
    "Waiting for the pizza delivery like...",
    "That awkward moment when...",
    "When you thought you muted yourself on Zoom",
    "My brain cells trying to work on a Friday",
    "The struggle is real",
    "Just five more minutes...",
    "When you accidentally like an old photo",
    "Trying to explain tech to my parents",
    "When the snack drawer is empty",
    "Is it Friday yet?",
    "When you hear the ice cream truck",
    "Trying to be productive after lunch",
    "When someone says 'we need to talk'",
    "Me pretending to understand",
    "When you see the bill",
    "What my teacher thinks I'm doing vs. reality",
    "When someone eats your labeled leftovers",
    "Trying to look natural in photos",
    "When the group project is due tomorrow",
    "My reaction to surprise plans",
    "When autocorrect strikes again",
    "POV: you forgot someone's name immediately",
    "When Mom uses your full name",
    "Trying to cook from a recipe for the first time",
    "That one friend who's always late",
    "When you find money in your old jacket",
    "Social media vs. reality",
    "When the elevator opens and it's full of people",
    "Running to catch the bus... and missing it",
    "Me after saying 'I'll start Monday'",
    "When the teacher picks you and you weren't listening",
    "POV: you're the only one who dressed up",
    "That look when someone takes the last slice",
    "Me googling my symptoms at 2 AM",
    "When the 'quick meeting' hits the 1-hour mark",
    "Waving back at someone who wasn't waving at you",
    "When your phone dies at 1% mid-text",
    "Me pretending to stretch so I can check the clock",
    "When you hear your name in someone else's conversation",
    "Trying to remember if you locked the door",
    "When the 'short cut' adds 30 extra minutes",
    "POV: your alarm didn't go off",
    "When you accidentally open the front camera",
    "Me in the group chat at 3 AM",
    "When the package says 'out for delivery'",
    "Telling yourself 'just one more episode'",
    "My pet judging my life choices",
    "When someone says 'Can I ask you something?'",
    "Me vs. assembling IKEA furniture",
    "When the song in your head turns out to be a bop",
    "That face when the food is too hot but too good to stop",
    "Walking past the same person 3 times in a grocery store",
    "When your charger only works at that one angle",
    "Me trying to sneak snacks into the theater",
    "When you accidentally send to the wrong chat",
    "POV: you parked and forgot where",
    "Nailed it. (Narrator: they did not nail it)",
  
    // ── Expansion Pack ──
    "When the snack drawer is empty.",
    "POV: You just woke up.",
    "Me trying to remember where I put it.",
    "My brain on Mondays.",
    "That awkward moment during a video call.",
    "When your pet does something weird.",
    "The sound of the ice cream truck.",
    "My reaction to any math problem.",
    "Waiting for the microwave to ding.",
    "When the teacher says 'group project.'",
    "POV: You finally get to relax.",
    "Me before my first cup of coffee.",
    "That feeling when you lose your phone.",
    "The last chip in the bag.",
    "When your printer runs out of ink.",
    "My face seeing the giant spider.",
    "Trying to sneak a treat past the dog.",
    "When the internet connection is slow.",
    "POV: You hear your favorite song.",
    "Me after five minutes of chores.",
    "The alarm clock on Saturday morning.",
    "When you finally finish homework.",
    "That look your cat gives you.",
    "My personal space invasion.",
    "When the food is finally ready.",
    "POV: You open the fridge.",
    "Me explaining a simple concept.",
    "The joy of new socks.",
    "When you find money in old clothes.",
    "My brain buffering mid-sentence.",
    "That moment of pure relief.",
    "The struggle of putting on a duvet cover.",
    "When your younger sibling copies you.",
    "POV: Your parent walks in.",
    "Me trying to ignore my responsibilities.",
    "The satisfying click of a cap.",
    "When the remote is missing.",
    "My dog hearing a treat bag crinkle.",
    "Trying to look busy at work/school.",
    "When you step on a Lego.",
    "POV: The last slice of pizza.",
    "Me attempting to parallel park.",
    "My happy dance for good news.",
    "When you accidentally hit 'reply all'.",
    "My reaction to any unexpected noise.",
    "That feeling of a fresh haircut.",
    "When your favorite show has a cliffhanger.",
    "POV: You're alone in the house.",
    "Me trying to remember a password.",
    "The moment the movie starts buffering.",
    "When you get a new notification.",
    "The struggle of opening a new jar.",
    "Trying to reach something on the top shelf.",
    "When the ice dispenser gets stuck.",
    "POV: Your turn on the game console.",
    "Me after a long day of pretending.",
    "The pure bliss of a warm blanket.",
    "When you find the perfect parking spot.",
    "My internal monologue during a test.",
    "That first sip of cold water.",
  ],
  2: [
    // Edgy / snarky
    "That's what she said",
    "Trying to be subtle but failing spectacularly",
    "My therapist is going to hear about this",
    "Just a little bit of trauma, as a treat",
    "When you sent that text to the wrong person",
    "My search history at 3 AM",
    "Asking for a friend... who is definitely me",
    "When the red flags look like normal flags",
    "Trying to keep it together after one too many",
    "My dating life in a nutshell",
    "When you thought it was a compliment",
    "My body is a temple of questionable decisions",
    "When you're overthinking at 3 AM",
    "The morning after",
    "Pretty sure that's a felony",
    "Trying to flirt but you're just awkward",
    "I swear I'm a good person",
    "When your ex texts 'hey'",
    "My bank account judging me",
    "When they say 'let's just be friends'",
    "Me pretending everything is fine",
    "Sunday scaries hitting different",
    "When you realize you peaked in high school",
    "Corporate wants you to find the difference",
    "Toxic trait unlocked",
    "When someone replies 'k'",
    "Main character energy gone wrong",
    "My last brain cell at 2 AM",
    "When you ARE the drama",
    "Plot twist nobody asked for",
    "Gaslight, gatekeep, girlboss",
    "Live, laugh, lose it",
    "When the vibes are off",
    "Catch me outside energy",
    "When you accidentally overshare",
    "My toxic trait is thinking I can fix them",
    "Relationship status: complicated with my WiFi",
    "When your horoscope personally attacks you",
    "Forgot the meds this morning and it SHOWS",
    "When you stalk too deep and like a 2019 photo",
    "My emotional support energy drink",
    "One bad decision away from a great story",
    "When the 'no drama' person IS the drama",
    "Telling my therapist about my week and even they look concerned",
    "POV: you just saw your ex's new partner",
    "When your coping mechanism needs a coping mechanism",
    "I'm not arguing, I'm passionately explaining why I'm right",
    "When you realize you've become the person you judged",
    "My impulse purchases judging me from the corner",
    "POV: you're the group chat's content",
    "Trust issues? I call it pattern recognition",
    "My comfort show for the 47th time",
    "When you get called 'bestie' by someone you met twice",
    "Deleting the paragraph and sending 'lol ok'",
    "When you overhear gossip and it's about you",
    "My brain writing fanfic about things that'll never happen",
    "The audacity of this Monday",
    "When you say 'I'm fine' and your eye twitches",
    "Online shopping at 2 AM: 'I deserve this'",
    "When the 'seen' notification hits but no reply comes",
  
    // ── Expansion Pack ──
    "When you see your ex's new post.",
    "POV: First date going horribly wrong.",
    "Me after one glass of wine.",
    "My therapist's next session agenda.",
    "That 'read' receipt from someone you like.",
    "When the passive aggression levels up.",
    "POV: You just sent a risky text.",
    "Me pretending to know what's happening.",
    "My boss asking for 'quick five minutes'.",
    "That moment of post-online shopping regret.",
    "When the dating app algorithm fails you.",
    "POV: You successfully avoided eye contact.",
    "Me trying to look busy at work.",
    "The 3 AM existential dread hits.",
    "When someone asks about your life plans.",
    "My face when the bill arrives.",
    "That moment you realize you're old.",
    "POV: Another Monday morning meeting.",
    "Me after scrolling social media too long.",
    "The struggle of responding to a vague text.",
    "When your phone dies mid-argument.",
    "My internal scream during a presentation.",
    "That friend who always overshares.",
    "POV: You just heard some juicy gossip.",
    "Me remembering all my past mistakes.",
    "The sweet embrace of a hangover cure.",
    "When your boundaries are non-existent.",
    "My brain replaying cringe moments.",
    "That 'Are we serious?' look.",
    "POV: Someone's giving unsolicited advice.",
    "Me after successfully gaslighting myself.",
    "The internal debate of sending a text.",
    "When your bank account mocks you.",
    "My therapist trying to hide their shock.",
    "That moment you spot your frenemy.",
    "POV: You're trying to ignore the red flags.",
    "Me attempting to be a functioning adult.",
    "The energy of a full inbox.",
    "When your entire personality is sarcasm.",
    "My social battery is officially dead.",
    "That moment of awkward small talk.",
    "POV: You just accidentally liked an old post.",
    "Me scrolling through my ex's stories.",
    "The sheer audacity of some people.",
    "When your toxic traits align perfectly.",
    "My face when someone says 'team building.'",
    "That moment before you hit 'send.'",
    "POV: You're pretending to listen.",
    "Me explaining my chaotic weekend.",
    "The weight of Monday morning.",
    "When you're too emotionally invested.",
    "My inner critic on overdrive.",
    "That feeling of being utterly drained.",
    "POV: You just saw the group chat drama.",
    "Me after confronting my problems.",
    "The sweet relief of cancelling plans.",
    "When your online persona crashes.",
    "My response to 'How are you doing?'",
    "That moment of profound regret.",
    "POV: You just got ghosted.",
  ],
  3: [
    // Unhinged / chaotic
    "I've made a huge mistake",
    "My fight or flight chose 'freeze and stare blankly'",
    "The voices told me to do it",
    "This is fine. Everything is fine.",
    "Pretty sure I peaked in kindergarten",
    "When the existential dread hits at 2 PM on a Tuesday",
    "I talked to my houseplants today. They judged me.",
    "Just another Tuesday in the apocalypse",
    "My therapist just retired. Coincidence?",
    "Pretty sure I'm in a simulation and the devs stopped caring",
    "I regret nothing... yet",
    "My brain cells actively self-destructing",
    "The last brain cell holding it all together",
    "Welcome to my mental breakdown: the musical",
    "Get help. But make it aesthetic.",
    "Society when I'm in charge",
    "God creating me at 3 AM on a weekday",
    "Satan called. He wants his vibe back.",
    "Born to chill, forced to adult",
    "Sleep paralysis demon checking in",
    "When you dissociate mid-conversation",
    "Me gaslighting myself into thinking I'm fine",
    "Chaos goblin mode: ACTIVATED",
    "My obituary is going to be wild",
    "The intrusive thoughts won today",
    "This is my villain origin story",
    "Weaponized incompetence",
    "Feral behavior, but make it professional",
    "Screaming into the void on company time",
    "My comfort zone is a war zone",
    "Unhinged and thriving",
    "Emotionally unavailable but still here",
    "Rock bottom has a basement",
    "POV: you've given up but in a fun way",
    "Core memory: unlocked and traumatic",
    "Normal people scare me more than this does",
    "My survival instincts are purely decorative",
    "I contain multitudes and they're all tired",
    "The urge to simply vanish into the woods",
    "My red flags have red flags",
    "I'm not a threat, I'm a promise",
    "Just blacked out and bought a plane ticket",
    "Every day I stray further from sanity",
    "The demons are winning and honestly they've earned it",
    "Running on spite and expired energy drinks",
    "My personality is barely controlled chaos",
    "This timeline is the darkest one and I have proof",
    "I am both the problem and the solution",
    "Manifesting my downfall in HD",
    "My emotional range is 'fine' to 'feral'",
    "Living proof that natural selection gave up",
    "If I had a dollar for every red flag I ignored I could afford therapy",
    "I am one minor inconvenience away from becoming a cryptid",
    "The WiFi went out and I saw my family. They seem nice.",
    "POV: you are the cautionary tale",
    "I don't have a plan. I barely have a pulse.",
    "Accidentally became the family disappointment speedrun any%",
    "Normalize screaming into a pillow as a strategy",
    "My comfort zone left the chat",
    "Somebody come get me I'm in a food coma and I can't move",
  
    // ── Expansion Pack ──
    "This is my villain origin story.",
    "My brain at 3 AM: *static noise*.",
    "Just embraced the goblin mode.",
    "The feral urge to destroy.",
    "Unsupervised and fully caffeinated.",
    "I'm not okay, I'm just existing.",
    "POV: You've been awake too long.",
    "Me accepting my fate as a cryptid.",
    "The void stares back, and it's me.",
    "When the screams become whispers.",
    "My brain: 'What if you just... ran?'",
    "That feeling of being a glitch in the matrix.",
    "POV: Your inner demons take the wheel.",
    "Me questioning everything I know.",
    "The chaos is a comforting presence.",
    "When you haven't slept in days.",
    "My spirit animal is a gremlin.",
    "That moment of absolute mental collapse.",
    "POV: You're speaking in tongues.",
    "Me descending into madness, gracefully.",
    "The abyss is calling, and I must answer.",
    "When the intrusive thoughts win.",
    "My internal monologue is a horror movie.",
    "That feeling of unraveling completely.",
    "POV: You've lost all sense of time.",
    "Me plotting my escape from reality.",
    "The quiet hum of impending doom.",
    "When your sanity is hanging by a thread.",
    "My brain just hit factory reset.",
    "That primal urge to scream into the void.",
    "POV: You're becoming the main character.",
    "Me before my final form.",
    "The sweet release of not caring anymore.",
    "When the universe demands chaos.",
    "My brain cells spontaneously combusting.",
    "That moment of serene derangement.",
    "POV: You've gone full feral.",
    "Me collecting evidence for my memoir.",
    "The overwhelming urge to hibernate forever.",
    "When you're powered by spite.",
    "My brain running on pure caffeine and chaos.",
    "That feeling of impending doom, but make it fashion.",
    "POV: You're now a cryptid.",
    "Me trying to remember my own name.",
    "The sweet sound of internal screaming.",
    "When the mask finally slips.",
    "My brain is a static TV screen.",
    "That feeling of being utterly unhinged.",
    "POV: You've embraced the darkness within.",
    "Me talking to myself in public.",
    "The sweet embrace of nihilism.",
    "When your sanity decides to take a vacation.",
    "My last two brain cells fighting.",
    "That moment before the primal scream.",
    "POV: You're losing your grip on reality.",
    "Me deciding to be a problem.",
    "The quiet desperation of existence.",
    "When your internal monologue gets loud.",
    "My brain is a broken record player.",
    "That feeling of being completely unbothered.",
  ],
};

// Filter to only memes whose image files actually exist on disk
const availableMemes = memeCards.filter(card => {
  const filename = card.imageUrl.split('/').pop();
  return fs.existsSync(path.join(MEME_DIR, filename));
});
console.log(`[Meme Melee] ${availableMemes.length}/${memeCards.length} meme images available`);

export { availableMemes };

// Spice algorithm:
//   Level 1 (Family Fun)  = only spice 1 content
//   Level 2 (Spicy)       = spice 1 + spice 2 content
//   Level 3 (Unhinged)    = spice 2 + spice 3 content (NO family fun)
function getSpiceLevels(spiceLevel) {
  if (spiceLevel === 1) return [1];
  if (spiceLevel === 2) return [1, 2];
  return [2, 3]; // unhinged
}

export function buildMemeDeck(spiceLevel = 1) {
  const levels = getSpiceLevels(spiceLevel);
  let allCaptions = [];
  for (const lvl of levels) {
    if (captionCards[lvl]) allCaptions = allCaptions.concat(captionCards[lvl]);
  }
  // Filter meme images by spice level too
  const filteredMemes = availableMemes.filter(m => levels.includes(m.spice || 1));
  return {
    blackCards: filteredMemes.length > 0 ? [...filteredMemes] : [...availableMemes],
    whiteCards: allCaptions,
  };
}
