// Meme Melee — Card Deck
// "Black cards" are meme images, "White cards" are caption cards

// Meme image prompts — these get fed to Imagen to generate meme-worthy images
// Each has a filename reference that maps to client/public/images/meme-melee/
export const memeCards = [
  { imageUrl: '/images/meme-melee/meme-01.png', alt: 'stressed pigeon in business suit', pick: 1 },
  { imageUrl: '/images/meme-melee/meme-02.png', alt: 'surprised lion cub', pick: 1 },
  { imageUrl: '/images/meme-melee/meme-03.png', alt: 'elderly person confused by phone', pick: 1 },
  { imageUrl: '/images/meme-melee/meme-04.png', alt: 'cool dog on beach', pick: 1 },
  { imageUrl: '/images/meme-melee/meme-05.png', alt: 'cat demanding food at table', pick: 1 },
  { imageUrl: '/images/meme-melee/meme-06.png', alt: 'superhero squirrel on acorn', pick: 1 },
  { imageUrl: '/images/meme-melee/meme-07.png', alt: 'sloth running marathon', pick: 1 },
  { imageUrl: '/images/meme-melee/meme-08.png', alt: 'ducks graduating', pick: 1 },
  { imageUrl: '/images/meme-melee/meme-09.png', alt: 'giraffe hiding behind bush', pick: 1 },
  { imageUrl: '/images/meme-melee/meme-10.png', alt: 'bear baking disaster', pick: 1 },
  { imageUrl: '/images/meme-melee/meme-11.png', alt: 'hamster driving monster truck', pick: 1 },
  { imageUrl: '/images/meme-melee/meme-12.png', alt: 'sheep doing yoga', pick: 1 },
  { imageUrl: '/images/meme-melee/meme-13.png', alt: 'alien tourist selfie', pick: 1 },
  { imageUrl: '/images/meme-melee/meme-14.png', alt: 'grumpy octopus king', pick: 1 },
  { imageUrl: '/images/meme-melee/meme-15.png', alt: 'eagle dropping fry', pick: 1 },
  { imageUrl: '/images/meme-melee/meme-16.png', alt: 'office workers in animal costumes', pick: 1 },
  { imageUrl: '/images/meme-melee/meme-17.png', alt: 'cat wizard casting spell', pick: 1 },
  { imageUrl: '/images/meme-melee/meme-18.png', alt: 'person failing to open jar', pick: 1 },
  { imageUrl: '/images/meme-melee/meme-19.png', alt: 'child drawing come to life', pick: 1 },
  { imageUrl: '/images/meme-melee/meme-20.png', alt: 'gnome backyard party', pick: 1 },
];

// Prompts to generate each meme image (used by generate-memes.js)
export const memePrompts = [
  'A highly stressed pigeon wearing a tiny business suit, frantically typing on a laptop with multiple overflowing coffee cups, surrounded by crumpled papers. Photorealistic style, dramatic lighting.',
  'A majestic lion cub making an extremely surprised face, eyes wide, mouth open in a perfect O of shock. Close-up portrait, nature photography style.',
  'An elderly person holding a smartphone upside down with a look of utter confusion and mild panic, wearing reading glasses on their forehead. Candid photo style.',
  'A dog wearing oversized sunglasses and a Hawaiian shirt, sipping a tiny cocktail with a straw, utterly relaxed on a miniature beach towel. Vibrant colors.',
  'A cat sitting at a dinner table with a knife and fork, staring intently and very displeased at an empty plate, demanding food with its eyes. Dramatic lighting like a Renaissance painting.',
  'A squirrel in a flowing superhero cape, striking a dramatic pose on top of a giant acorn, looking overly confident and slightly ridiculous. Action movie poster style.',
  'A very tired-looking sloth attempting to run a marathon, barely moving, with sweat dripping dramatically and a look of existential dread. Sports photography style.',
  'A group of ducks in a perfect single-file line, all wearing tiny graduation caps and serious scholarly expressions, marching towards a library.',
  'A bewildered giraffe trying to hide behind a ridiculously small garden bush, with most of its neck and head clearly visible, looking embarrassed.',
  'A chef hat-wearing bear trying to bake a cake, but the kitchen is a complete disaster: flour explosions, burnt pans, and a look of bewildered despair on its face.',
  'A tiny hamster driving a monster truck through a miniature obstacle course made of household items, looking intensely focused and determined.',
  'A very fluffy sheep attempting to do an advanced yoga pose, tied in a knot, looking utterly perplexed and slightly stuck.',
  'An alien tourist with oversized eyes taking a selfie in front of a completely mundane rusty fire hydrant, looking absolutely thrilled.',
  'A grumpy octopus wearing a tiny crooked crown, sitting on a throne made of seashells, looking immensely annoyed by its subjects.',
  'A majestic eagle dramatically dropping a single french fry from its talons, looking utterly distraught and heartbroken as it falls.',
  'A group of office workers in various ridiculous animal costumes like a gorilla, a flamingo, and a unicorn, having a very serious corporate meeting around a boardroom table.',
  'A cat wearing a tiny sparkling wizard hat, attempting to cast a spell with an outstretched paw, surrounded by a faint magical glow and a mischievous grin.',
  'A person dramatically failing at opening a jar of pickles, with a look of utter defeat, sweat, and bulging arm veins. Dramatic close-up.',
  'A child drawing of a monster brought to life, looking confused and slightly embarrassed to be existing in the real world. Mixed media style.',
  'A group of garden gnomes throwing a wild tiny backyard party with disco lights, a miniature boombox, and tiny party hats.',
];

// Caption cards (white cards) by spice level
const captionCards = {
  1: [
    "When the WiFi goes out.",
    "Me trying to adult.",
    "My face when I realize it's Monday.",
    "Waiting for the pizza delivery.",
    "That awkward moment when...",
    "When you thought you muted yourself.",
    "My brain cells trying to work on a Friday.",
    "The struggle is real.",
    "Just five more minutes.",
    "When you accidentally like an old photo.",
    "My pet's reaction to anything.",
    "Trying to explain tech to my parents.",
    "When the snack drawer is empty.",
    "My alarm clock vs. my soul.",
    "Is it Friday yet?",
    "When you hear the ice cream truck.",
    "Trying to be productive.",
    "When someone says 'we need to talk.'",
    "Me pretending to understand.",
    "When you see the bill.",
    "What my teacher thinks I'm doing vs. what I'm actually doing.",
    "When someone eats the leftovers you were saving.",
    "Trying to look natural in photos.",
    "When the group project is due tomorrow.",
    "My reaction to surprise plans.",
    "When autocorrect strikes again.",
    "POV: you forgot someone's name.",
    "When Mom uses your full name.",
    "Trying to cook from a recipe.",
    "That one friend who's always late.",
    "When you find money in your pocket.",
    "Social media vs. reality.",
    "When the store is out of your favorite snack.",
    "Me vs. responsibilities.",
    "When someone says 'no offense but...'",
  ],
  2: [
    "That's what she said.",
    "Trying to be subtle but failing spectacularly.",
    "My therapist is going to hear about this.",
    "Just a little bit of trauma, as a treat.",
    "When you sent that text to the wrong person.",
    "My search history at 3 AM.",
    "Asking for a friend.",
    "When the red flags look like normal flags.",
    "Trying to keep it together after a few too many.",
    "My dating life in a nutshell.",
    "When you thought it was a compliment.",
    "My body is a temple... of questionable decisions.",
    "When you're overthinking everything.",
    "The morning after.",
    "Pretty sure that's a felony.",
    "Trying to flirt but you're just awkward.",
    "I swear I'm a good person.",
    "When your ex texts 'hey.'",
    "My bank account judging me.",
    "When they say 'let's just be friends.'",
    "Me pretending everything is fine.",
    "Sunday scaries hitting different.",
    "When you realize you peaked in high school.",
    "Corporate wants you to find the difference.",
    "Toxic trait unlocked.",
    "When someone replies 'k.'",
    "Main character energy gone wrong.",
    "My last brain cell at 2 AM.",
    "When you're the drama.",
    "Plot twist nobody asked for.",
    "Gaslight, gatekeep, girlboss.",
    "Live, laugh, lose it.",
    "When the vibes are off.",
    "Catch me outside energy.",
    "When you accidentally overshare.",
  ],
  3: [
    "I've made a huge mistake.",
    "My fight or flight chose 'freeze and stare blankly.'",
    "The voices told me to do it.",
    "This is fine. Everything is fine.",
    "Pretty sure I peaked in kindergarten.",
    "When the existential dread hits at 2 PM.",
    "I talked to my houseplants today. They judged me.",
    "Just another Tuesday in the apocalypse.",
    "My therapist just retired. Coincidence?",
    "Pretty sure I'm in a simulation.",
    "I regret nothing... yet.",
    "My brain cells actively committing hari-kari.",
    "The last brain cell holding it all together.",
    "Welcome to my mental breakdown.",
    "Get help. But make it ✨ aesthetic ✨",
    "Society when I'm in charge.",
    "God creating me at 3 AM on a weekday.",
    "Satan called. He wants his vibe back.",
    "Born to chill, forced to adult.",
    "Sleep paralysis demon checking in.",
    "When you dissociate mid-conversation.",
    "Me gaslighting myself.",
    "Chaos goblin mode: activated.",
    "My obituary is going to be wild.",
    "The intrusive thoughts won today.",
    "This is my villain origin story.",
    "Weaponized incompetence.",
    "Feral behavior, but make it professional.",
    "Screaming into the void on company time.",
    "My comfort zone is a war zone.",
    "Unhinged and thriving.",
    "Emotionally unavailable but still here.",
    "Rock bottom has a basement.",
    "POV: you've given up but in a fun way.",
    "Core memory: unlocked and traumatic.",
  ],
};

export function buildMemeDeck(spiceLevel = 1) {
  // Collect caption cards for the given spice level and below
  let allCaptions = [];
  for (let lvl = 1; lvl <= spiceLevel; lvl++) {
    if (captionCards[lvl]) allCaptions = allCaptions.concat(captionCards[lvl]);
  }
  return {
    blackCards: [...memeCards],  // meme images as "black cards"
    whiteCards: allCaptions,     // captions as "white cards"
  };
}
