// Pre-generated emoji rebus puzzles for High-roglyphics
// Organized by topic pack — each puzzle has answer, emojis, hint (category), and alternates

export const PUZZLES = {
  standard: [
    { answer: 'Star Wars', emojis: '⭐⚔️🌌🚀', hint: 'Movie', alternates: ['starwars'] },
    { answer: 'Harry Potter', emojis: '🧙‍♂️⚡📚🏰', hint: 'Movie', alternates: ['harry potter and the'] },
    { answer: 'Pizza', emojis: '🍕🧀🍅🔥', hint: 'Food', alternates: ['pizza pie'] },
    { answer: 'Titanic', emojis: '🚢❄️💔🌊', hint: 'Movie', alternates: [] },
    { answer: 'Frozen', emojis: '❄️👸⛄🎵', hint: 'Movie', alternates: ['frozen the movie'] },
    { answer: 'Monopoly', emojis: '🎩💰🏠🎲', hint: 'Game', alternates: [] },
    { answer: 'Superman', emojis: '💪🦸‍♂️🅰️☁️', hint: 'Superhero', alternates: ['super man'] },
    { answer: 'Beyonce', emojis: '👑🐝🎤💃', hint: 'Celebrity', alternates: ['beyoncé', 'queen bey', 'queen bee'] },
    { answer: 'Breaking Bad', emojis: '💔👨‍🔬💎🏜️', hint: 'TV Show', alternates: ['breakingbad'] },
    { answer: 'The Lion King', emojis: '🦁👑🌅🎵', hint: 'Movie', alternates: ['lion king'] },
    { answer: 'Jaws', emojis: '🦈🏖️😱🌊', hint: 'Movie', alternates: [] },
    { answer: 'Minecraft', emojis: '⛏️🧱🌳🐷', hint: 'Game', alternates: ['mine craft'] },
    { answer: 'Michael Jackson', emojis: '🧤🕺👑🎵', hint: 'Celebrity', alternates: ['mj', 'king of pop'] },
    { answer: 'Taylor Swift', emojis: '🎤❤️🐍🎸', hint: 'Celebrity', alternates: ['tswift', 't swift'] },
    { answer: 'Hot Dog', emojis: '🌭🔥🐕', hint: 'Food', alternates: ['hotdog'] },
    { answer: 'Game of Thrones', emojis: '⚔️👑🐉❄️', hint: 'TV Show', alternates: ['got', 'thrones'] },
    { answer: 'Mario Kart', emojis: '🏎️🍄⭐🏁', hint: 'Game', alternates: ['mariokart'] },
    { answer: 'Ice Cream', emojis: '🍦❄️🍨😋', hint: 'Food', alternates: ['icecream'] },
    { answer: 'Jurassic Park', emojis: '🦖🏞️🔬🚙', hint: 'Movie', alternates: ['jurassic world'] },
    { answer: 'Goldilocks', emojis: '👧🐻🥣🛏️', hint: 'Story', alternates: ['goldilocks and the three bears'] },
    { answer: 'The Olympics', emojis: '🏅🔥🌍🏃', hint: 'Event', alternates: ['olympics', 'olympic games'] },
    { answer: 'Spider-Man', emojis: '🕷️🦸‍♂️🕸️🏙️', hint: 'Superhero', alternates: ['spiderman', 'spider man'] },
    { answer: 'Elon Musk', emojis: '🚀🤖💰🔴', hint: 'Celebrity', alternates: ['musk'] },
    { answer: 'Finding Nemo', emojis: '🐠🔍🌊👨‍👦', hint: 'Movie', alternates: ['nemo'] },
    { answer: 'The Wizard of Oz', emojis: '🧙‍♂️🌈👠🌪️', hint: 'Movie', alternates: ['wizard of oz'] },
    { answer: 'Rock Paper Scissors', emojis: '🪨📄✂️🤜', hint: 'Game', alternates: ['rps', 'rock paper scissor'] },
    { answer: 'Sushi', emojis: '🍣🐟🍚🥢', hint: 'Food', alternates: [] },
    { answer: 'Batman', emojis: '🦇🦸‍♂️🌃🃏', hint: 'Superhero', alternates: ['bat man', 'the batman'] },
    { answer: 'Forrest Gump', emojis: '🏃🍫🦐🪖', hint: 'Movie', alternates: [] },
    { answer: 'The Avengers', emojis: '🦸‍♂️🦸‍♀️🛡️🔨💥', hint: 'Movie', alternates: ['avengers'] },
    { answer: 'Pac-Man', emojis: '🟡👻🍒🕹️', hint: 'Game', alternates: ['pacman', 'pac man'] },
    { answer: 'Stranger Things', emojis: '🚲💡👾🔦', hint: 'TV Show', alternates: [] },
    { answer: 'Instagram', emojis: '📸🌅❤️📱', hint: 'App', alternates: ['insta'] },
    { answer: 'Olympics', emojis: '🏊🏃🥇🔥', hint: 'Event', alternates: ['the olympics', 'olympic games'] },
    { answer: 'Netflix', emojis: '📺🍿🛋️🔴', hint: 'Brand', alternates: ['netflix and chill'] },
    { answer: 'Wonder Woman', emojis: '👸⚔️⭐🛡️', hint: 'Superhero', alternates: ['wonderwoman'] },
    { answer: 'Taco', emojis: '🌮🧀🌶️🥑', hint: 'Food', alternates: ['tacos'] },
    { answer: 'The Simpsons', emojis: '👨‍👩‍👧‍👦🍩🟡📺', hint: 'TV Show', alternates: ['simpsons'] },
    { answer: 'James Bond', emojis: '🕵️🔫🍸🚗', hint: 'Movie', alternates: ['007', 'bond'] },
    { answer: 'Football', emojis: '🏈🏟️🏆🍺', hint: 'Sport', alternates: ['american football', 'nfl'] },
    { answer: 'Emoji Movie', emojis: '😀🎬📱💩', hint: 'Movie', alternates: ['the emoji movie'] },
    { answer: 'Chocolate', emojis: '🍫🤤😋🟤', hint: 'Food', alternates: [] },
    { answer: 'Up', emojis: '🎈🏠👴🐕', hint: 'Movie', alternates: [] },
    { answer: 'Ghostbusters', emojis: '👻🚫🔫🚗', hint: 'Movie', alternates: ['ghost busters'] },
    { answer: 'Lebron James', emojis: '🏀👑💪🐐', hint: 'Celebrity', alternates: ['lebron', 'king james'] },
    { answer: 'Tetris', emojis: '🧱🔲🔳⬇️', hint: 'Game', alternates: [] },
    { answer: 'Ratatouille', emojis: '🐀👨‍🍳🍳🇫🇷', hint: 'Movie', alternates: [] },
    { answer: 'Shark Tank', emojis: '🦈💰💼📺', hint: 'TV Show', alternates: [] },
    { answer: 'Hamburger', emojis: '🍔🐄🧀🍅', hint: 'Food', alternates: ['burger', 'cheeseburger'] },
    { answer: 'Scooby Doo', emojis: '🐕🔍👻🚐', hint: 'TV Show', alternates: ['scooby-doo', 'scoobydoo'] },
    { answer: 'Oprah', emojis: '📺👑🎤📖', hint: 'Celebrity', alternates: ['oprah winfrey'] },
    { answer: 'Candy Crush', emojis: '🍬💥📱⭐', hint: 'Game', alternates: [] },
    { answer: 'Tom and Jerry', emojis: '🐱🐭💥😂', hint: 'TV Show', alternates: ['tom & jerry'] },
    { answer: 'Birthday Party', emojis: '🎂🎈🎁🥳', hint: 'Event', alternates: ['birthday'] },
  ],

  scifi: [
    { answer: 'Star Trek', emojis: '⭐🖖🚀🌌', hint: 'TV Show', alternates: ['startrek'] },
    { answer: 'E.T.', emojis: '👽☎️🏠🚲', hint: 'Movie', alternates: ['et', 'e.t. the extra-terrestrial', 'et the extra terrestrial'] },
    { answer: 'The Matrix', emojis: '💊🕶️💻🔫', hint: 'Movie', alternates: ['matrix'] },
    { answer: 'Aliens', emojis: '👽👽🚀😱', hint: 'Movie', alternates: ['alien'] },
    { answer: 'Doctor Who', emojis: '🩺📞🔵⏰', hint: 'TV Show', alternates: ['dr who', 'dr. who'] },
    { answer: 'Lightsaber', emojis: '💡⚔️✨🟢', hint: 'Weapon', alternates: ['light saber', 'light sabre'] },
    { answer: 'Terminator', emojis: '🤖💀🔫🕶️', hint: 'Movie', alternates: ['the terminator'] },
    { answer: 'Space Station', emojis: '🚀🏠🌍⭐', hint: 'Space', alternates: ['international space station', 'iss'] },
    { answer: 'Moon Landing', emojis: '🌙🚀👨‍🚀🇺🇸', hint: 'Event', alternates: ['the moon landing', 'apollo 11'] },
    { answer: 'Darth Vader', emojis: '😈⚫💨🗡️', hint: 'Character', alternates: ['vader'] },
    { answer: 'Blade Runner', emojis: '🔪🏃🤖🌧️', hint: 'Movie', alternates: [] },
    { answer: 'UFO', emojis: '🛸👽❓🌌', hint: 'Concept', alternates: ['unidentified flying object', 'flying saucer'] },
    { answer: 'Mars', emojis: '🔴🌍🚀🏜️', hint: 'Planet', alternates: ['the red planet'] },
    { answer: 'Death Star', emojis: '💀⭐💥🌍', hint: 'Object', alternates: ['deathstar'] },
    { answer: 'Time Machine', emojis: '⏰⚙️🔀🕰️', hint: 'Concept', alternates: ['the time machine'] },
    { answer: 'Hitchhiker\'s Guide to the Galaxy', emojis: '👍📕🌌🐬', hint: 'Book', alternates: ['hitchhikers guide', 'hitchhiker\'s guide'] },
    { answer: 'Guardians of the Galaxy', emojis: '🦝🌳🚀🌌💫', hint: 'Movie', alternates: ['guardians', 'gotg'] },
    { answer: 'Wall-E', emojis: '🤖🗑️🌱💕', hint: 'Movie', alternates: ['wall e', 'walle'] },
    { answer: 'Interstellar', emojis: '🌽🕳️⏰🌊', hint: 'Movie', alternates: [] },
    { answer: 'Black Mirror', emojis: '📱📺⚫😱', hint: 'TV Show', alternates: [] },
    { answer: 'Dune', emojis: '🏜️🐛👁️🪐', hint: 'Movie', alternates: [] },
    { answer: 'Back to the Future', emojis: '🔙🚗⚡🕐', hint: 'Movie', alternates: ['bttf'] },
    { answer: 'The Mandalorian', emojis: '🪖👶🏜️🚀', hint: 'TV Show', alternates: ['mandalorian', 'mando'] },
    { answer: 'Cyberpunk', emojis: '🤖🌃💉🕶️', hint: 'Genre', alternates: ['cyberpunk 2077'] },
    { answer: 'Fifth Element', emojis: '5️⃣🔥💧🌬️🪨', hint: 'Movie', alternates: ['the fifth element'] },
    { answer: 'Alien vs Predator', emojis: '👽⚔️🎯💀', hint: 'Movie', alternates: ['avp', 'alien vs. predator'] },
    { answer: 'Gravity', emojis: '👩‍🚀🌍💫😰', hint: 'Movie', alternates: [] },
    { answer: '2001 A Space Odyssey', emojis: '🐒🦴🚀🖥️', hint: 'Movie', alternates: ['2001', 'space odyssey'] },
    { answer: 'Battlestar Galactica', emojis: '🚀⚔️🤖🌌', hint: 'TV Show', alternates: ['bsg'] },
    { answer: 'Robocop', emojis: '👮🤖🔫🏙️', hint: 'Movie', alternates: ['robo cop'] },
    { answer: 'Tron', emojis: '🏍️💿💡🕹️', hint: 'Movie', alternates: [] },
    { answer: 'Arrival', emojis: '🛸🔤👩‍🔬🌎', hint: 'Movie', alternates: [] },
    { answer: 'Warp Speed', emojis: '🚀💨⭐⚡', hint: 'Concept', alternates: ['warp drive'] },
    { answer: 'Yoda', emojis: '🟢🧓⚔️🌌', hint: 'Character', alternates: ['master yoda'] },
    { answer: 'Avatar', emojis: '🟦🌳🐲🏹', hint: 'Movie', alternates: [] },
    { answer: 'Westworld', emojis: '🤠🤖🏜️🧠', hint: 'TV Show', alternates: ['west world'] },
    { answer: 'Alien', emojis: '👽🩸🚀😱', hint: 'Movie', alternates: ['aliens'] },
    { answer: 'Teleportation', emojis: '💫🚶✨🏠', hint: 'Concept', alternates: ['teleport'] },
    { answer: 'Saturn', emojis: '🪐💍🌌⭐', hint: 'Planet', alternates: [] },
    { answer: 'Starship', emojis: '⭐🚢🌌👨‍🚀', hint: 'Concept', alternates: ['star ship'] },
    { answer: 'The Expanse', emojis: '🚀🪐⚔️🌌', hint: 'TV Show', alternates: ['expanse'] },
    { answer: 'Predator', emojis: '👹🌴🔫💀', hint: 'Movie', alternates: ['the predator'] },
    { answer: 'R2-D2', emojis: '🤖🔵⚪🔧', hint: 'Character', alternates: ['r2d2', 'artoo'] },
    { answer: 'Asteroid', emojis: '🪨🌍💥🌌', hint: 'Space', alternates: ['asteroids'] },
    { answer: 'Jupiter', emojis: '🟤🌑🔴🌌', hint: 'Planet', alternates: [] },
    { answer: 'Spock', emojis: '🖖👂🔵🧪', hint: 'Character', alternates: ['mr spock'] },
    { answer: 'Clones', emojis: '👤👤👤🧬', hint: 'Concept', alternates: ['clone', 'attack of the clones'] },
    { answer: 'District 9', emojis: '🦐👽🏚️🔫', hint: 'Movie', alternates: [] },
    { answer: 'Meteor', emojis: '☄️🔥🌍💥', hint: 'Space', alternates: ['meteorite'] },
  ],

  fantasy: [
    { answer: 'Lord of the Rings', emojis: '💍👑🧙‍♂️🌋', hint: 'Movie', alternates: ['lotr', 'lord of the ring'] },
    { answer: 'Dragon', emojis: '🐉🔥🏰✨', hint: 'Creature', alternates: ['dragons'] },
    { answer: 'Unicorn', emojis: '🦄🌈✨💖', hint: 'Creature', alternates: ['unicorns'] },
    { answer: 'King Arthur', emojis: '👑⚔️🏰🛡️', hint: 'Legend', alternates: ['arthur'] },
    { answer: 'Dungeons and Dragons', emojis: '🐉🏰⚔️🎲', hint: 'Game', alternates: ['d&d', 'dnd', 'dungeons & dragons'] },
    { answer: 'Wizard', emojis: '🧙‍♂️✨⚡📚', hint: 'Character', alternates: ['wizards'] },
    { answer: 'Treasure Map', emojis: '🗺️💰☠️🏝️', hint: 'Object', alternates: ['treasure'] },
    { answer: 'Fairy Tale', emojis: '🧚✨📖👸', hint: 'Concept', alternates: ['fairy tales', 'fairytale'] },
    { answer: 'Excalibur', emojis: '⚔️🪨👑✨', hint: 'Legend', alternates: [] },
    { answer: 'The Princess Bride', emojis: '👸💒⚔️❤️', hint: 'Movie', alternates: ['princess bride'] },
    { answer: 'Narnia', emojis: '🚪❄️🦁👑', hint: 'Movie', alternates: ['the chronicles of narnia', 'chronicles of narnia'] },
    { answer: 'Merlin', emojis: '🧙‍♂️🔮⚡🦉', hint: 'Character', alternates: [] },
    { answer: 'Phoenix', emojis: '🔥🐦💀↩️', hint: 'Creature', alternates: ['the phoenix'] },
    { answer: 'Sleeping Beauty', emojis: '😴💤👸💋', hint: 'Movie', alternates: [] },
    { answer: 'Zelda', emojis: '🧝‍♂️⚔️🏰💎', hint: 'Game', alternates: ['legend of zelda', 'the legend of zelda'] },
    { answer: 'Knight in Shining Armor', emojis: '🛡️⚔️✨🐴', hint: 'Phrase', alternates: ['knight in shining armour', 'knight'] },
    { answer: 'World of Warcraft', emojis: '🌍⚔️🧌🗡️', hint: 'Game', alternates: ['wow', 'warcraft'] },
    { answer: 'Shrek', emojis: '🟢👹🏰💚', hint: 'Movie', alternates: [] },
    { answer: 'Pirates of the Caribbean', emojis: '🏴‍☠️⚔️🚢💀🌴', hint: 'Movie', alternates: ['pirates', 'potc'] },
    { answer: 'Robin Hood', emojis: '🏹🦊🌲💰', hint: 'Legend', alternates: ['robinhood'] },
    { answer: 'The Hobbit', emojis: '🧑‍🦲🗡️🐉💍', hint: 'Movie', alternates: ['hobbit'] },
    { answer: 'Game of Thrones', emojis: '👑🗡️🐉❄️🔥', hint: 'TV Show', alternates: ['got', 'thrones'] },
    { answer: 'Medusa', emojis: '🐍👩🪨👀', hint: 'Myth', alternates: [] },
    { answer: 'Thor', emojis: '⚡🔨💪🌩️', hint: 'Character', alternates: [] },
    { answer: 'Magic Carpet', emojis: '🧞‍♂️🧶✨🌙', hint: 'Object', alternates: ['aladdin', 'magic carpet ride'] },
    { answer: 'Cinderella', emojis: '👸👠🎃🕛', hint: 'Movie', alternates: [] },
    { answer: 'Snow White', emojis: '👸🍎🪞🐿️', hint: 'Movie', alternates: ['snow white and the seven dwarfs'] },
    { answer: 'Rapunzel', emojis: '👸🏰💇‍♀️🌸', hint: 'Movie', alternates: ['tangled'] },
    { answer: 'Gandalf', emojis: '🧙‍♂️⚪🗡️🔥', hint: 'Character', alternates: ['gandalf the grey', 'gandalf the white'] },
    { answer: 'Centaur', emojis: '🧑🐴⚔️🌲', hint: 'Creature', alternates: ['centaurs'] },
    { answer: 'Gryphon', emojis: '🦅🦁👑✨', hint: 'Creature', alternates: ['griffin', 'griffon'] },
    { answer: 'Beauty and the Beast', emojis: '🌹👸🐻📚', hint: 'Movie', alternates: ['batb'] },
    { answer: 'Potion', emojis: '🧪✨💜🧙‍♀️', hint: 'Object', alternates: ['potions', 'magic potion'] },
    { answer: 'Goblin', emojis: '👺💰🏔️😈', hint: 'Creature', alternates: ['goblins'] },
    { answer: 'Elf', emojis: '🧝‍♂️🏹🌲👂', hint: 'Creature', alternates: ['elves'] },
    { answer: 'Labyrinth', emojis: '🌀🧩🏰👑', hint: 'Movie', alternates: ['the labyrinth'] },
    { answer: 'Kraken', emojis: '🦑🌊🚢😱', hint: 'Creature', alternates: ['the kraken'] },
    { answer: 'Mulan', emojis: '⚔️👸🐉🎎', hint: 'Movie', alternates: [] },
    { answer: 'Enchanted Forest', emojis: '🌲✨🦌🧚', hint: 'Place', alternates: ['enchanted woods'] },
    { answer: 'Camelot', emojis: '🏰👑⚔️🛡️', hint: 'Legend', alternates: [] },
    { answer: 'Minotaur', emojis: '🐮🌀💀⚔️', hint: 'Myth', alternates: ['the minotaur'] },
    { answer: 'Gollum', emojis: '💍👀🐟🏔️', hint: 'Character', alternates: ['smeagol'] },
    { answer: 'Peter Pan', emojis: '🧒🧚✨🪝', hint: 'Story', alternates: [] },
    { answer: 'Cupid', emojis: '👶🏹❤️💘', hint: 'Myth', alternates: [] },
    { answer: 'Atlantis', emojis: '🏛️🌊💎🔱', hint: 'Legend', alternates: ['the lost city of atlantis'] },
    { answer: 'Ogre', emojis: '🟢👹🏔️🍖', hint: 'Creature', alternates: ['ogres'] },
    { answer: 'The Witcher', emojis: '⚔️🧪🐺💀', hint: 'TV Show', alternates: ['witcher', 'geralt'] },
    { answer: 'Pegasus', emojis: '🐴🪶☁️✨', hint: 'Creature', alternates: [] },
    { answer: 'Quest', emojis: '🗺️⚔️🏆🐉', hint: 'Concept', alternates: ['adventure'] },
  ],

  nostalgia: [
    { answer: 'Tamagotchi', emojis: '🥚👾💀🔋', hint: 'Toy', alternates: ['tamagochi'] },
    { answer: 'Spice Girls', emojis: '🌶️👧👧👧👧👧', hint: 'Band', alternates: ['spice girls band'] },
    { answer: 'Friends', emojis: '☕🛋️👫🏙️', hint: 'TV Show', alternates: ['friends tv show'] },
    { answer: 'Nokia', emojis: '📱🐍🧱💪', hint: 'Phone', alternates: ['nokia phone', 'nokia 3310'] },
    { answer: 'Backstreet Boys', emojis: '🔙🛣️👦🎤', hint: 'Band', alternates: ['bsb'] },
    { answer: 'Pokemon', emojis: '⚡🐭🔴⚪', hint: 'Game', alternates: ['pokémon', 'pokemon go'] },
    { answer: 'Fresh Prince', emojis: '🤴🏠🚕🏀', hint: 'TV Show', alternates: ['fresh prince of bel air', 'fresh prince of bel-air'] },
    { answer: 'Floppy Disk', emojis: '💾📦💻🔲', hint: 'Tech', alternates: ['floppy disc', 'floppy'] },
    { answer: 'MSN Messenger', emojis: '💻💬🦋😎', hint: 'App', alternates: ['msn', 'windows messenger'] },
    { answer: 'Napster', emojis: '🎵🐱💻🏴‍☠️', hint: 'App', alternates: [] },
    { answer: 'Dial Up Internet', emojis: '📞📡💻🐌', hint: 'Tech', alternates: ['dial up', 'dialup', 'dial-up'] },
    { answer: 'Blockbuster', emojis: '🎬📼🏪🎥', hint: 'Store', alternates: ['blockbuster video'] },
    { answer: 'Beanie Babies', emojis: '🧸❤️💰🏷️', hint: 'Toy', alternates: ['beanie baby'] },
    { answer: 'Rugrats', emojis: '👶👶🍼🏠', hint: 'TV Show', alternates: [] },
    { answer: 'Furby', emojis: '🦉👀🗣️🔋', hint: 'Toy', alternates: ['furbies'] },
    { answer: 'Walkman', emojis: '🎵📼🎧🚶', hint: 'Tech', alternates: ['sony walkman'] },
    { answer: 'MySpace', emojis: '💻👤🎵🌟', hint: 'App', alternates: ['my space', 'myspace.com'] },
    { answer: 'Britney Spears', emojis: '🎤👧🐍💋', hint: 'Celebrity', alternates: ['britney'] },
    { answer: 'The Sims', emojis: '🏠👨‍👩‍👧💬🎮', hint: 'Game', alternates: ['sims'] },
    { answer: 'Dunkaroos', emojis: '🦘🍪🍫😋', hint: 'Snack', alternates: [] },
    { answer: 'Boy Band', emojis: '👦👦👦🎤💃', hint: 'Music', alternates: ['boyband'] },
    { answer: 'Titanic', emojis: '🚢💑🧊🌊', hint: 'Movie', alternates: [] },
    { answer: 'Saved by the Bell', emojis: '🔔🏫📚😎', hint: 'TV Show', alternates: ['saved by the bell'] },
    { answer: 'Lisa Frank', emojis: '🦄🌈✏️💜', hint: 'Brand', alternates: [] },
    { answer: 'Oregon Trail', emojis: '🤠🐂🏔️💀', hint: 'Game', alternates: ['the oregon trail'] },
    { answer: 'Etch A Sketch', emojis: '🔴🖊️📺🎨', hint: 'Toy', alternates: ['etch-a-sketch'] },
    { answer: 'AIM', emojis: '💬🏃💛💻', hint: 'App', alternates: ['aol instant messenger', 'aim messenger'] },
    { answer: 'Razor Scooter', emojis: '🛴💨🦵😤', hint: 'Toy', alternates: ['razor'] },
    { answer: 'TRL', emojis: '📺🏆🎵📞', hint: 'TV Show', alternates: ['total request live'] },
    { answer: 'Boombox', emojis: '📻🔊🎵💪', hint: 'Tech', alternates: ['boom box'] },
    { answer: 'Seinfeld', emojis: '🧑‍🤝‍🧑☕🏙️🍕', hint: 'TV Show', alternates: [] },
    { answer: 'Game Boy', emojis: '🎮🟩👦🔋', hint: 'Tech', alternates: ['gameboy'] },
    { answer: 'Destiny\'s Child', emojis: '👧👧👧🎤💫', hint: 'Band', alternates: ['destinys child'] },
    { answer: 'Roller Blades', emojis: '🛼💨🌈😎', hint: 'Toy', alternates: ['rollerblades', 'inline skates'] },
    { answer: 'Pager', emojis: '📟🔢📞🏃', hint: 'Tech', alternates: ['beeper'] },
    { answer: 'Buffy', emojis: '🧛🗡️👧🌙', hint: 'TV Show', alternates: ['buffy the vampire slayer'] },
    { answer: 'Lava Lamp', emojis: '🫧🔴💡🌈', hint: 'Object', alternates: [] },
    { answer: 'NSYNC', emojis: '👦👦👦👦👦🎤', hint: 'Band', alternates: ['n sync', "n'sync"] },
    { answer: 'Geocities', emojis: '🌐🏗️💻⭐', hint: 'Website', alternates: ['geo cities'] },
    { answer: 'Happy Meal', emojis: '🍔🎁😊🤡', hint: 'Food', alternates: ['mcdonalds happy meal'] },
    { answer: 'Dawson\'s Creek', emojis: '🚣😢💋🏘️', hint: 'TV Show', alternates: ['dawsons creek'] },
    { answer: 'Cassette Tape', emojis: '📼🎵✏️⏪', hint: 'Tech', alternates: ['cassette', 'tape'] },
    { answer: 'Power Rangers', emojis: '🦸‍♂️🦸‍♀️🦕🤖', hint: 'TV Show', alternates: ['mighty morphin power rangers'] },
    { answer: 'Skip It', emojis: '🦵🔵💨🎵', hint: 'Toy', alternates: ['skipit'] },
    { answer: 'Eminem', emojis: '🍬🎤😤🖕', hint: 'Celebrity', alternates: ['slim shady', 'marshall mathers'] },
    { answer: 'Discman', emojis: '💿🎧🔊🚶', hint: 'Tech', alternates: ['disc man', 'portable cd player'] },
    { answer: 'Bill Nye', emojis: '🧑‍🔬🧪📺🌍', hint: 'Celebrity', alternates: ['bill nye the science guy'] },
    { answer: 'Slime', emojis: '🟢💧🫠👐', hint: 'Toy', alternates: ['nickelodeon slime'] },
    { answer: 'Full House', emojis: '🏠👨‍👧‍👧👶📺', hint: 'TV Show', alternates: [] },
  ],

  horror: [
    { answer: 'Dracula', emojis: '🧛🦇🩸🌙', hint: 'Monster', alternates: ['count dracula', 'vampire'] },
    { answer: 'Zombie', emojis: '🧟🧠🩸💀', hint: 'Monster', alternates: ['zombies'] },
    { answer: 'Friday the 13th', emojis: '📅1️⃣3️⃣🔪', hint: 'Movie', alternates: ['friday the thirteenth'] },
    { answer: 'Haunted House', emojis: '🏚️👻😱🕯️', hint: 'Place', alternates: ['haunted mansion'] },
    { answer: 'The Shining', emojis: '❄️🪓👦🏨', hint: 'Movie', alternates: ['shining'] },
    { answer: 'Frankenstein', emojis: '⚡🧟🔩🧪', hint: 'Movie', alternates: ['frankensteins monster'] },
    { answer: 'Nightmare on Elm Street', emojis: '😴🔪🧤🏘️', hint: 'Movie', alternates: ['a nightmare on elm street', 'freddy krueger'] },
    { answer: 'Werewolf', emojis: '🐺🌕😱🦴', hint: 'Monster', alternates: ['were wolf', 'lycanthrope'] },
    { answer: 'The Exorcist', emojis: '📿👧🔄😈', hint: 'Movie', alternates: ['exorcist'] },
    { answer: 'It', emojis: '🤡🎈🕷️😱', hint: 'Movie', alternates: ['pennywise', 'it the movie'] },
    { answer: 'Scream', emojis: '😱📞🔪👻', hint: 'Movie', alternates: ['ghostface'] },
    { answer: 'Poltergeist', emojis: '📺👻🏠😱', hint: 'Movie', alternates: [] },
    { answer: 'Witch', emojis: '🧙‍♀️🧹🐈‍⬛🌙', hint: 'Monster', alternates: ['witches', 'the witch'] },
    { answer: 'Skeleton', emojis: '💀🦴👻⚰️', hint: 'Monster', alternates: ['skeletons'] },
    { answer: 'Voodoo Doll', emojis: '🧸📌💀😈', hint: 'Object', alternates: ['voodoo'] },
    { answer: 'Texas Chainsaw Massacre', emojis: '🪚🩸🏚️😱', hint: 'Movie', alternates: ['chainsaw massacre', 'leatherface'] },
    { answer: 'The Ring', emojis: '📼📺👻💀', hint: 'Movie', alternates: ['ring', 'ringu'] },
    { answer: 'Saw', emojis: '🧩🔪🩸🤡', hint: 'Movie', alternates: ['jigsaw'] },
    { answer: 'Cemetery', emojis: '⚰️🪦🌙🦇', hint: 'Place', alternates: ['graveyard'] },
    { answer: 'Ouija Board', emojis: '🔤👻🕯️😱', hint: 'Object', alternates: ['ouija', 'ouija board'] },
    { answer: 'Mummy', emojis: '🏛️🩹👁️🏜️', hint: 'Monster', alternates: ['the mummy'] },
    { answer: 'Candyman', emojis: '🍬🪝🐝🪞', hint: 'Movie', alternates: ['candy man'] },
    { answer: 'Get Out', emojis: '🏃🧠🫖😱', hint: 'Movie', alternates: [] },
    { answer: 'The Silence of the Lambs', emojis: '🐑🤐🦋😈', hint: 'Movie', alternates: ['silence of the lambs'] },
    { answer: 'Black Cat', emojis: '🐈‍⬛🌙🍀😱', hint: 'Superstition', alternates: ['black cats'] },
    { answer: 'The Conjuring', emojis: '🏚️👫📿😈', hint: 'Movie', alternates: ['conjuring'] },
    { answer: 'Hellraiser', emojis: '📦🔗😈🩸', hint: 'Movie', alternates: ['pinhead'] },
    { answer: 'Nosferatu', emojis: '🧛🌑🚢🩸', hint: 'Movie', alternates: [] },
    { answer: 'Paranormal Activity', emojis: '📹🛏️👻📺', hint: 'Movie', alternates: [] },
    { answer: 'Chucky', emojis: '🧸🔪😈👶', hint: 'Movie', alternates: ['child\'s play', 'childs play'] },
    { answer: 'Final Destination', emojis: '💀🔮😱✈️', hint: 'Movie', alternates: [] },
    { answer: 'Pennywise', emojis: '🤡🎈🕷️🚿', hint: 'Character', alternates: ['it'] },
    { answer: 'Bloody Mary', emojis: '🪞🩸👻🕯️', hint: 'Legend', alternates: [] },
    { answer: 'Nightmare', emojis: '😴👹💀😱', hint: 'Concept', alternates: ['nightmares'] },
    { answer: 'The Walking Dead', emojis: '🧟🚶💀🏚️', hint: 'TV Show', alternates: ['walking dead', 'twd'] },
    { answer: 'Swamp Thing', emojis: '🌿🏚️👹💧', hint: 'Character', alternates: ['swamp creature'] },
    { answer: 'Full Moon', emojis: '🌕🐺🌌😱', hint: 'Concept', alternates: [] },
    { answer: 'The Omen', emojis: '👦😈6️⃣6️⃣6️⃣', hint: 'Movie', alternates: ['omen'] },
    { answer: 'Cabin in the Woods', emojis: '🏚️🌲😱🎰', hint: 'Movie', alternates: ['cabin'] },
    { answer: 'Insidious', emojis: '👨‍👩‍👦😱🔴👻', hint: 'Movie', alternates: [] },
    { answer: 'Annabelle', emojis: '🧸👗😈🔒', hint: 'Movie', alternates: [] },
    { answer: 'The Babadook', emojis: '📖🎩👹🚪', hint: 'Movie', alternates: ['babadook'] },
    { answer: 'Silver Bullet', emojis: '🔫🐺🌕💀', hint: 'Weapon', alternates: [] },
    { answer: 'Garlic', emojis: '🧄🧛🚫😤', hint: 'Weapon', alternates: [] },
    { answer: 'Alien', emojis: '👽🩸🚀😱', hint: 'Movie', alternates: ['aliens'] },
    { answer: 'Psycho', emojis: '🚿🔪🏨😱', hint: 'Movie', alternates: ['norman bates'] },
    { answer: 'Rosemary\'s Baby', emojis: '🤰😈👶🔮', hint: 'Movie', alternates: ['rosemarys baby'] },
    { answer: 'Headless Horseman', emojis: '🐴🎃⚔️🌙', hint: 'Legend', alternates: ['sleepy hollow'] },
    { answer: 'Crypt Keeper', emojis: '⚰️💀😂📺', hint: 'Character', alternates: ['tales from the crypt'] },
  ],

  science: [
    { answer: 'DNA', emojis: '🧬🔬🧪👶', hint: 'Science', alternates: ['deoxyribonucleic acid'] },
    { answer: 'Rocket Science', emojis: '🚀🧪🧠💥', hint: 'Concept', alternates: [] },
    { answer: 'Periodic Table', emojis: '📊⚗️🧪📚', hint: 'Science', alternates: ['periodic table of elements'] },
    { answer: 'Evolution', emojis: '🐒🚶‍♂️🧬📈', hint: 'Science', alternates: ['theory of evolution', 'darwin'] },
    { answer: 'Electricity', emojis: '⚡🔌💡🔋', hint: 'Science', alternates: ['electric'] },
    { answer: 'Chemistry', emojis: '⚗️🧪💥🔬', hint: 'Science', alternates: [] },
    { answer: 'Solar System', emojis: '☀️🪐🌍🌙', hint: 'Space', alternates: ['the solar system'] },
    { answer: 'Atom', emojis: '⚛️🔬💥🔵', hint: 'Science', alternates: ['atoms'] },
    { answer: 'Telescope', emojis: '🔭⭐🌙👀', hint: 'Tool', alternates: [] },
    { answer: 'Einstein', emojis: '👴🧠💡📝', hint: 'Scientist', alternates: ['albert einstein'] },
    { answer: 'Laboratory', emojis: '🥼🧪🔬🧬', hint: 'Place', alternates: ['lab'] },
    { answer: 'Global Warming', emojis: '🌍🔥📈😰', hint: 'Concept', alternates: ['climate change'] },
    { answer: 'Artificial Intelligence', emojis: '🤖🧠💻🔮', hint: 'Tech', alternates: ['ai', 'a.i.'] },
    { answer: 'Photosynthesis', emojis: '🌱☀️💧🍃', hint: 'Science', alternates: [] },
    { answer: 'Virus', emojis: '🦠😷🤧💀', hint: 'Science', alternates: ['viruses'] },
    { answer: 'Newton', emojis: '🍎⬇️📐🧑‍🔬', hint: 'Scientist', alternates: ['isaac newton', 'sir isaac newton'] },
    { answer: 'Volcano', emojis: '🌋🔥💥🏔️', hint: 'Nature', alternates: ['volcanoes'] },
    { answer: 'Microscope', emojis: '🔬👀🦠🧫', hint: 'Tool', alternates: [] },
    { answer: 'Lightning', emojis: '⚡☁️🌩️💥', hint: 'Nature', alternates: ['thunder and lightning'] },
    { answer: 'Dinosaur', emojis: '🦕🦴🌿🏔️', hint: 'Animal', alternates: ['dinosaurs', 'dino'] },
    { answer: 'Black Hole', emojis: '⚫🕳️🌌⚡', hint: 'Space', alternates: ['blackhole'] },
    { answer: 'Robot', emojis: '🤖⚡🔧🏭', hint: 'Tech', alternates: ['robots'] },
    { answer: 'Gravity', emojis: '🍎⬇️🌍🌙', hint: 'Science', alternates: [] },
    { answer: 'Space Shuttle', emojis: '🚀🛬🌍👨‍🚀', hint: 'Vehicle', alternates: ['shuttle'] },
    { answer: 'Big Bang', emojis: '💥🌌⭐🔭', hint: 'Theory', alternates: ['the big bang', 'big bang theory'] },
    { answer: 'Magnet', emojis: '🧲🔴🔵⚡', hint: 'Science', alternates: ['magnets'] },
    { answer: 'Hydrogen', emojis: '💧🔬💥🎈', hint: 'Element', alternates: ['h2'] },
    { answer: 'Mars Rover', emojis: '🔴🤖🛞📸', hint: 'Space', alternates: ['curiosity', 'perseverance', 'rover'] },
    { answer: 'Tsunami', emojis: '🌊🌊🏘️😱', hint: 'Nature', alternates: ['tidal wave'] },
    { answer: 'MRI', emojis: '🧲🧠📸🏥', hint: 'Tech', alternates: ['magnetic resonance'] },
    { answer: 'Fossil', emojis: '🦴🪨🔍🦕', hint: 'Science', alternates: ['fossils'] },
    { answer: 'Earthquake', emojis: '🌍💥🏚️😱', hint: 'Nature', alternates: ['quake'] },
    { answer: 'Test Tube', emojis: '🧪💧🔬👨‍🔬', hint: 'Tool', alternates: ['test tubes'] },
    { answer: 'Wifi', emojis: '📶📱💻🌐', hint: 'Tech', alternates: ['wi-fi', 'wi fi', 'wireless'] },
    { answer: 'Supernova', emojis: '⭐💥🌌✨', hint: 'Space', alternates: ['super nova'] },
    { answer: 'Battery', emojis: '🔋⚡📱🔌', hint: 'Tech', alternates: ['batteries'] },
    { answer: 'Tornado', emojis: '🌪️🏠💨😱', hint: 'Nature', alternates: ['twister'] },
    { answer: 'Satellite', emojis: '📡🌍🛰️📺', hint: 'Tech', alternates: ['satellites'] },
    { answer: 'Stethoscope', emojis: '🩺❤️👂🏥', hint: 'Tool', alternates: [] },
    { answer: 'Nuclear', emojis: '☢️💥⚡🏭', hint: 'Science', alternates: ['nuclear energy', 'nuclear power'] },
    { answer: 'Comet', emojis: '☄️❄️🌌⭐', hint: 'Space', alternates: ['comets'] },
    { answer: 'Thermometer', emojis: '🌡️🔴❄️🤒', hint: 'Tool', alternates: [] },
    { answer: 'Pangaea', emojis: '🌍🧩🦕🗺️', hint: 'Science', alternates: ['pangea'] },
    { answer: 'Solar Eclipse', emojis: '☀️🌑🌍😎', hint: 'Event', alternates: ['eclipse'] },
    { answer: 'Hubble', emojis: '🔭🌌📸🛰️', hint: 'Space', alternates: ['hubble telescope', 'hubble space telescope'] },
    { answer: 'Genome', emojis: '🧬📖🔬🧑‍🔬', hint: 'Science', alternates: ['human genome'] },
    { answer: 'Tsunami Warning', emojis: '⚠️🌊📡🏃', hint: 'Concept', alternates: [] },
    { answer: 'Oxygen', emojis: '💨🫁🌿❤️', hint: 'Element', alternates: ['o2'] },
    { answer: 'Tesla', emojis: '⚡🚗🔋🧑‍🔬', hint: 'Scientist', alternates: ['nikola tesla', 'tesla motors'] },
  ],
};
